from __future__ import annotations

import argparse
import math
import sys
import traceback
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


COMPLETE_FLAG = "PHASE_N3PF_MS_SEED2_AB_AUDIT_RERUN_COMPLETE.flag"
STOP_FLAGS = {
    "eval_failed": "PHASE_N3PF_MS_AB_STOP_EVAL_FAILED.flag",
    "diagnostics_failed": "PHASE_N3PF_MS_AB_STOP_FEATURE_GPSI_DIAGNOSTICS_FAILED.flag",
    "watcher_failed": "PHASE_N3PF_MS_AB_STOP_WATCHER_FAILED.flag",
}


class AnalysisStop(Exception):
    def __init__(self, reason: str, detail: str) -> None:
        super().__init__(detail)
        self.reason = reason
        self.detail = detail


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Analyze Phase N3PF-MS-AB audit and rerun sanity.")
    parser.add_argument("--result-dir", default="results/env_v2_phase_n3pf_ms_seed2_ab_audit_rerun")
    parser.add_argument("--source-result-dir", default="results/env_v2_phase_n3pf_ms_multiseed")
    parser.add_argument("--attention-success", type=float, default=0.6033)
    parser.add_argument("--attention-collision", type=float, default=0.3967)
    parser.add_argument("--noz-success", type=float, default=0.5667)
    parser.add_argument("--noz-collision", type=float, default=0.4333)
    parser.add_argument("--p3-s0-success", type=float, default=0.6167)
    parser.add_argument("--p3-s0-collision", type=float, default=0.3833)
    parser.add_argument("--p3-s1-success", type=float, default=0.6089)
    parser.add_argument("--p3-s1-collision", type=float, default=0.3911)
    parser.add_argument("--p3-s2-success", type=float, default=0.4222)
    parser.add_argument("--p3-s2-collision", type=float, default=0.5778)
    return parser.parse_args()


def rel(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def read_csv(path: Path) -> pd.DataFrame:
    if not path.exists() or path.stat().st_size == 0:
        raise FileNotFoundError(f"missing or empty CSV: {rel(path)}")
    return pd.read_csv(path)


def write_stop(result_dir: Path, reason: str, detail: str) -> None:
    flag = STOP_FLAGS.get(reason, STOP_FLAGS["diagnostics_failed"])
    write_text(result_dir / flag, f"{reason}\n{detail.strip()}\n")
    write_text(result_dir / "phase_n3pf_ms_seed2_ab_status.txt", f"stopped:{flag}\n")
    write_text(
        result_dir / "PHASE_N3PF_MS_SEED2_AB_AUDIT_RERUN_REPORT.md",
        "\n".join(
            [
                "# Phase N3PF-MS-AB Seed2 Collapse Audit + Minimal Rerun Sanity",
                "",
                f"`terminal_decision = phase_n3pf_ms_seed2_ab_stopped_{reason}`",
                "",
                "Partial report generated by final analysis.",
                "",
                "```text",
                detail.strip(),
                "```",
            ]
        )
        + "\n",
    )


def fmt(value: Any) -> str:
    try:
        f = float(value)
    except Exception:
        return str(value)
    if math.isnan(f):
        return "nan"
    return f"{f:.4f}"


def table_md(df: pd.DataFrame, cols: list[str], max_rows: int = 24) -> list[str]:
    if df.empty:
        return ["No rows."]
    cols = [col for col in cols if col in df.columns]
    lines = ["| " + " | ".join(cols) + " |", "| " + " | ".join(["---"] * len(cols)) + " |"]
    for _, row in df[cols].head(max_rows).iterrows():
        lines.append("| " + " | ".join(fmt(row[col]) if isinstance(row[col], (float, int, np.floating, np.integer)) else str(row[col]) for col in cols) + " |")
    return lines


def validate(result_dir: Path) -> None:
    step_a = result_dir / "step_a_audit/tables"
    step_b = result_dir / "step_b_rerun/tables"
    required_a = [
        "phase_n3pf_ms_seed2a_config_diff.csv",
        "phase_n3pf_ms_seed2a_checkpoint_path_audit.csv",
        "phase_n3pf_ms_seed2a_checkpoint_integrity_extended.csv",
        "phase_n3pf_ms_seed2a_intermediate_checkpoint_eval.csv",
        "phase_n3pf_ms_seed2a_training_curve_diagnostics.csv",
        "phase_n3pf_ms_seed2a_behavior_diagnostics.csv",
        "phase_n3pf_ms_seed2a_feature_gpsi_audit.csv",
        "phase_n3pf_ms_seed2a_decision.csv",
    ]
    required_b = [
        "phase_n3pf_ms_seed2b_rerun_config_manifest.csv",
        "phase_n3pf_ms_seed2b_command_manifest.csv",
        "phase_n3pf_ms_seed2b_resource_affinity.csv",
        "phase_n3pf_ms_seed2b_checkpoint_integrity.csv",
        "phase_n3pf_ms_seed2b_train_curve.csv",
        "phase_n3pf_ms_seed2b_eval_summary_aggregate.csv",
        "phase_n3pf_ms_seed2b_eval_summary_by_seed.csv",
        "phase_n3pf_ms_seed2b_scenario_breakdown.csv",
        "phase_n3pf_ms_seed2b_motion_mode_breakdown.csv",
        "phase_n3pf_ms_seed2b_threat_class_breakdown.csv",
        "phase_n3pf_ms_seed2b_raw_unsafe_action_summary.csv",
    ]
    missing = [f"step_a_audit/tables/{name}" for name in required_a if not (step_a / name).exists() or (step_a / name).stat().st_size == 0]
    missing.extend(f"step_b_rerun/tables/{name}" for name in required_b if not (step_b / name).exists() or (step_b / name).stat().st_size == 0)
    if missing:
        raise AnalysisStop("eval_failed", "missing required AB artifacts:\n" + "\n".join(missing))
    if not (result_dir / "phase_n3pf_ms_seed2_ab_watcher.log").exists():
        raise AnalysisStop("watcher_failed", "missing watcher log")


def select_metric(df: pd.DataFrame, method_key_contains: str, label: str = "1500k") -> tuple[float, float]:
    sub = df[(df["method_key"].astype(str).str.contains(method_key_contains, regex=False)) & (df["checkpoint_label"].astype(str) == label)]
    if sub.empty:
        return np.nan, np.nan
    row = sub.iloc[0]
    return float(row["mean_success_rate"]), float(row["mean_collision_rate"])


def behavior_diagnostics(result_dir: Path, source_dir: Path, args: argparse.Namespace) -> pd.DataFrame:
    old = read_csv(source_dir / "tables/phase_n3pf_ms_eval_summary_aggregate.csv")
    new = read_csv(result_dir / "step_b_rerun/tables/phase_n3pf_ms_seed2b_eval_summary_aggregate.csv")
    raw_new = read_csv(result_dir / "step_b_rerun/tables/phase_n3pf_ms_seed2b_raw_unsafe_action_summary.csv")
    rows: list[dict[str, Any]] = [
        {
            "policy": "p3_seed0_original_1500k",
            "success_rate": float(args.p3_s0_success),
            "collision_rate": float(args.p3_s0_collision),
            "source": "reported_baseline",
        },
        {
            "policy": "p3_seed1_original_1500k",
            "success_rate": float(args.p3_s1_success),
            "collision_rate": float(args.p3_s1_collision),
            "source": "reported_baseline",
        },
        {
            "policy": "p3_seed2_original_1500k",
            "success_rate": float(args.p3_s2_success),
            "collision_rate": float(args.p3_s2_collision),
            "source": "reported_baseline",
        },
        {
            "policy": "attention_full_reference",
            "success_rate": float(args.attention_success),
            "collision_rate": float(args.attention_collision),
            "source": "reported_baseline",
        },
        {
            "policy": "no_z_full_reference",
            "success_rate": float(args.noz_success),
            "collision_rate": float(args.noz_collision),
            "source": "reported_baseline",
        },
    ]
    for _, row in old[old["method_key"].astype(str).isin(["p3_s2_1000k", "p3_s2_1500k", "p3_s2_final"])].iterrows():
        rows.append(
            {
                "policy": str(row["method_key"]),
                "checkpoint_label": row.get("checkpoint_label", ""),
                "success_rate": float(row["mean_success_rate"]),
                "collision_rate": float(row["mean_collision_rate"]),
                "raw_unsafe_action_rate": float(row.get("mean_raw_unsafe_action_rate", np.nan)),
                "action_norm": float(row.get("mean_action_norm", np.nan)),
                "action_delta": float(row.get("mean_action_delta", np.nan)),
                "progress": float(row.get("mean_progress", np.nan)),
                "source": "N3PF-MS-original",
            }
        )
    for _, row in new.iterrows():
        raw_match = raw_new[raw_new["method_key"].astype(str) == str(row["method_key"])]
        rows.append(
            {
                "policy": str(row["method_key"]),
                "run_name": row.get("run_name", ""),
                "checkpoint_label": row.get("checkpoint_label", ""),
                "success_rate": float(row["mean_success_rate"]),
                "collision_rate": float(row["mean_collision_rate"]),
                "raw_unsafe_action_rate": float(row.get("mean_raw_unsafe_action_rate", np.nan)),
                "raw_min_predicted_cpa": float(raw_match["raw_min_predicted_cpa"].mean()) if not raw_match.empty and "raw_min_predicted_cpa" in raw_match else np.nan,
                "action_norm": float(row.get("mean_action_norm", np.nan)),
                "action_delta": float(row.get("mean_action_delta", np.nan)),
                "progress": float(row.get("mean_progress", np.nan)),
                "source": "N3PF-MS-AB-rerun",
            }
        )
    out = pd.DataFrame(rows)
    out.to_csv(result_dir / "step_b_rerun/tables/phase_n3pf_ms_seed2b_behavior_diagnostics.csv", index=False)
    return out


def decision(result_dir: Path, source_dir: Path, args: argparse.Namespace, behavior: pd.DataFrame) -> pd.DataFrame:
    step_a_decision = read_csv(result_dir / "step_a_audit/tables/phase_n3pf_ms_seed2a_decision.csv").iloc[0].to_dict()
    eval_agg = read_csv(result_dir / "step_b_rerun/tables/phase_n3pf_ms_seed2b_eval_summary_aggregate.csv")
    s2_success, s2_collision = select_metric(eval_agg, "seed2_rerunA", "1500k")
    seed3_success, seed3_collision = select_metric(eval_agg, "seed3_sanity", "1500k")
    seed2_recovered = bool(np.isfinite(s2_success) and s2_success >= 0.58 and np.isfinite(s2_collision) and s2_collision <= 0.42)
    seed2_collapsed = bool(np.isfinite(s2_success) and (s2_success < 0.50 or s2_collision > 0.50))
    seed3_run = bool(np.isfinite(seed3_success))
    seed3_healthy = bool(seed3_run and seed3_success >= 0.58 and seed3_collision <= 0.42)
    seed3_collapsed = bool(seed3_run and (seed3_success < 0.50 or seed3_collision > 0.50))

    if seed2_recovered and not seed3_run:
        likely = "original_seed2_bad_run_or_parallel_randomness_issue; rerun recovered but seed3 not run"
        restore = "conditional_no_until_additional_seed_or_transparent_replacement"
        n4u = "no"
        stabilization = "recommended"
    elif seed2_recovered and seed3_healthy:
        likely = "original_seed2_bad_run_or_parallel_randomness_issue"
        restore = "yes_with_transparent_reporting"
        n4u = "yes_after_recording_replacement_policy"
        stabilization = "not_required_before_N4U"
    elif seed2_collapsed and seed3_healthy:
        likely = "seed2_unlucky_but_architecture_seed_sensitive"
        restore = "no"
        n4u = "no"
        stabilization = "recommended"
    elif seed2_collapsed and (seed3_collapsed or not seed3_run):
        likely = "collapse_reproducible_or_inconclusive_architecture_instability"
        restore = "no"
        n4u = "no"
        stabilization = "required"
    else:
        likely = "inconclusive"
        restore = "no"
        n4u = "no"
        stabilization = "recommended"

    row = {
        "step_a_decision_type": step_a_decision.get("decision_type", ""),
        "step_a_hard_error_found": int(step_a_decision.get("hard_error_found", 0)),
        "step_b_executed": 1,
        "seed2_rerunA_success_1500k": s2_success,
        "seed2_rerunA_collision_1500k": s2_collision,
        "seed2_rerunA_recovered": int(seed2_recovered),
        "seed3_sanity_executed": int(seed3_run),
        "seed3_sanity_success_1500k": seed3_success,
        "seed3_sanity_collision_1500k": seed3_collision,
        "seed3_sanity_healthy": int(seed3_healthy),
        "collapse_most_likely_cause": likely,
        "allow_restore_p3_primary_n4_candidate": restore,
        "can_continue_N4U": n4u,
        "needs_p3_stabilization_phase": stabilization,
        "attention_full_multiseed_needed": "yes_before_decisive_attention_claim",
    }
    out = pd.DataFrame([row])
    out.to_csv(result_dir / "step_b_rerun/tables/phase_n3pf_ms_seed2b_decision.csv", index=False)
    return out


def plots(result_dir: Path, source_dir: Path, behavior: pd.DataFrame) -> None:
    plot_dir = result_dir / "step_b_rerun/plots"
    plot_dir.mkdir(parents=True, exist_ok=True)
    old = read_csv(source_dir / "tables/phase_n3pf_ms_eval_summary_aggregate.csv")
    new = read_csv(result_dir / "step_b_rerun/tables/phase_n3pf_ms_seed2b_eval_summary_aggregate.csv")
    rows = []
    for _, row in old[old["method_key"].astype(str).isin(["p3_s2_1000k", "p3_s2_1500k", "p3_s2_final"])].iterrows():
        rows.append({"series": "original_seed2", "label": row["checkpoint_label"], "success": row["mean_success_rate"], "collision": row["mean_collision_rate"]})
    for _, row in new[new["method_key"].astype(str).str.contains("seed2_rerunA")].iterrows():
        rows.append({"series": "seed2_rerunA", "label": row["checkpoint_label"], "success": row["mean_success_rate"], "collision": row["mean_collision_rate"]})
    curve = pd.DataFrame(rows)
    order = {"1000k": 0, "1500k": 1, "final": 2}
    plt.figure(figsize=(8.5, 4.4))
    for series, group in curve.groupby("series"):
        group = group.assign(_order=group["label"].map(order)).sort_values("_order")
        plt.plot(group["label"], group["success"], marker="o", label=f"{series} success")
        plt.plot(group["label"], group["collision"], marker="x", linestyle="--", label=f"{series} collision")
    plt.ylim(0, 1)
    plt.legend(fontsize=8)
    plt.tight_layout()
    plt.savefig(plot_dir / "seed2_original_vs_rerun_success_collision.png", dpi=140)
    plt.close()

    train = read_csv(result_dir / "step_b_rerun/tables/phase_n3pf_ms_seed2b_train_curve.csv")
    plt.figure(figsize=(8.5, 4.2))
    if "steps" in train and "episode_reward" in train:
        for run_name, group in train.groupby(train.get("run_name", pd.Series(["unknown"] * len(train)))):
            g = group.sort_values("steps")
            roll = pd.to_numeric(g["episode_reward"], errors="coerce").rolling(50, min_periods=1).mean()
            plt.plot(g["steps"], roll, label=str(run_name))
    plt.xlabel("steps")
    plt.ylabel("rolling episode reward")
    plt.legend(fontsize=8)
    plt.tight_layout()
    plt.savefig(plot_dir / "seed2_rerun_training_curve.png", dpi=140)
    plt.close()

    focus = behavior[behavior["policy"].astype(str).str.contains("seed2")]
    labels = focus["policy"].astype(str).tolist()
    x = np.arange(len(labels))
    plt.figure(figsize=(11, 4.5))
    width = 0.2
    for idx, metric in enumerate(["raw_unsafe_action_rate", "action_norm", "action_delta", "progress"]):
        vals = pd.to_numeric(focus.get(metric, pd.Series(dtype=float)), errors="coerce").fillna(0.0).to_numpy()
        plt.bar(x + (idx - 1.5) * width, vals, width, label=metric)
    plt.xticks(x, labels, rotation=25, ha="right")
    plt.legend(fontsize=8)
    plt.tight_layout()
    plt.savefig(plot_dir / "seed2_original_vs_rerun_behavior.png", dpi=140)
    plt.close()

    plt.figure(figsize=(7.5, 4.2))
    compare = behavior[behavior["policy"].astype(str).str.contains("rerunA|sanity", regex=True)]
    if compare.empty:
        plt.text(0.5, 0.5, "seed3_sanity not run", ha="center", va="center")
        plt.axis("off")
    else:
        plt.bar(compare["policy"], pd.to_numeric(compare["success_rate"], errors="coerce"), label="success")
        plt.plot(compare["policy"], pd.to_numeric(compare["collision_rate"], errors="coerce"), marker="o", color="tab:red", label="collision")
        plt.ylim(0, 1)
        plt.xticks(rotation=25, ha="right")
        plt.legend()
    plt.tight_layout()
    plt.savefig(plot_dir / "seed2_seed3_sanity_comparison.png", dpi=140)
    plt.close()


def collect_files(result_dir: Path) -> dict[str, list[str]]:
    return {
        "tables": [rel(path) for path in sorted(result_dir.glob("**/tables/*.csv"))],
        "plots": [rel(path) for path in sorted(result_dir.glob("**/plots/*.png"))],
        "logs": [rel(path) for path in sorted(result_dir.glob("**/*.log"))],
        "flags": [rel(path) for path in sorted(result_dir.glob("*.flag"))],
    }


def report(result_dir: Path, source_dir: Path, decision_df: pd.DataFrame, behavior: pd.DataFrame, files: dict[str, list[str]]) -> str:
    step_a = read_csv(result_dir / "step_a_audit/tables/phase_n3pf_ms_seed2a_decision.csv")
    config = read_csv(result_dir / "step_a_audit/tables/phase_n3pf_ms_seed2a_config_diff.csv")
    ckpt = read_csv(result_dir / "step_a_audit/tables/phase_n3pf_ms_seed2a_checkpoint_integrity_extended.csv")
    inter = read_csv(result_dir / "step_a_audit/tables/phase_n3pf_ms_seed2a_intermediate_checkpoint_eval.csv")
    eval_agg = read_csv(result_dir / "step_b_rerun/tables/phase_n3pf_ms_seed2b_eval_summary_aggregate.csv")
    scenario = read_csv(result_dir / "step_b_rerun/tables/phase_n3pf_ms_seed2b_scenario_breakdown.csv")
    motion = read_csv(result_dir / "step_b_rerun/tables/phase_n3pf_ms_seed2b_motion_mode_breakdown.csv")
    threat = read_csv(result_dir / "step_b_rerun/tables/phase_n3pf_ms_seed2b_threat_class_breakdown.csv")
    dec = decision_df.iloc[0].to_dict()
    lines = [
        "# Phase N3PF-MS-AB Seed2 Collapse Audit + Minimal Rerun Sanity",
        "",
        "## Terminal Decision",
        "",
        "`terminal_decision = phase_n3pf_ms_seed2_ab_audit_rerun_complete`",
        "",
        "## Step A Audit Summary",
        "",
    ]
    lines.extend(table_md(step_a, list(step_a.columns), max_rows=4))
    lines.extend(["", "No hard config/path/checkpoint/Gpsi feature error was allowed past Step A. Config equivalence and checkpoint integrity details are below.", ""])
    lines.extend(table_md(config, ["field", "seed1_value", "seed2_value", "same", "allowed_difference"], max_rows=28))
    lines.extend(["", "## Checkpoint Integrity", ""])
    lines.extend(table_md(ckpt, ["training_seed", "checkpoint_label", "exists", "model_num_timesteps", "optimizer_state_present", "policy_parameter_delta_vs_previous_checkpoint", "eval_seed_count", "scenario_count", "episode_count"], max_rows=18))
    lines.extend(["", "## Intermediate Eval", ""])
    lines.extend(table_md(inter, ["run_name", "training_seed", "method_key", "checkpoint_label", "num_eval_seeds", "num_episodes_total", "mean_success_rate", "mean_collision_rate", "mean_raw_unsafe_action_rate"], max_rows=24))
    lines.extend(["", "## Step B Rerun Result", ""])
    lines.extend(table_md(eval_agg, ["run_name", "training_seed", "method_key", "checkpoint_label", "num_eval_seeds", "num_episodes_total", "mean_success_rate", "mean_collision_rate", "mean_raw_unsafe_action_rate", "mean_action_delta"], max_rows=18))
    lines.extend(["", "## Decision", ""])
    lines.extend(table_md(decision_df, list(decision_df.columns), max_rows=3))
    lines.extend(
        [
            "",
            "Interpretation:",
            f"- engineering_error_found: {dec.get('step_a_hard_error_found', 'unknown')}",
            f"- seed2 collapse most likely cause: {dec.get('collapse_most_likely_cause', 'unknown')}",
            f"- seed2_rerunA recovered: {dec.get('seed2_rerunA_recovered', 'unknown')}",
            f"- seed3_sanity status: {'executed' if int(dec.get('seed3_sanity_executed', 0)) else 'not_run'}",
            f"- restore P3 primary N4 candidate: {dec.get('allow_restore_p3_primary_n4_candidate', 'unknown')}",
            f"- can continue N4-U: {dec.get('can_continue_N4U', 'unknown')}",
            f"- P3 stabilization phase: {dec.get('needs_p3_stabilization_phase', 'unknown')}",
            f"- attention_full multi-seed: {dec.get('attention_full_multiseed_needed', 'unknown')}",
            "",
            "## Behavior Diagnostics",
            "",
        ]
    )
    lines.extend(table_md(behavior, ["policy", "checkpoint_label", "success_rate", "collision_rate", "raw_unsafe_action_rate", "action_norm", "action_delta", "progress", "source"], max_rows=30))
    lines.extend(["", "## Scenario/Motion/Threat Summary", ""])
    lines.extend(table_md(scenario[scenario["checkpoint_label"].astype(str) == "1500k"], ["run_name", "method_key", "eval_seed", "scenario", "success_rate", "collision_rate"], max_rows=36))
    lines.extend(table_md(motion[motion["checkpoint_label"].astype(str) == "1500k"], ["run_name", "method_key", "eval_seed", "threat_motion_mode", "success_rate", "collision_rate"], max_rows=18))
    lines.extend(table_md(threat[threat["checkpoint_label"].astype(str) == "1500k"], ["run_name", "method_key", "eval_seed", "threat_class", "success_rate", "collision_rate"], max_rows=18))
    lines.extend(["", "## Artifacts", ""])
    for key in ["tables", "plots", "logs", "flags"]:
        lines.append(f"### {key}")
        values = files.get(key, [])
        lines.extend([f"- `{value}`" for value in values] if values else ["- none"])
    return "\n".join(lines) + "\n"


def main() -> None:
    args = parse_args()
    result_dir = ROOT / args.result_dir
    source_dir = ROOT / args.source_result_dir
    result_dir.mkdir(parents=True, exist_ok=True)
    try:
        validate(result_dir)
        behavior = behavior_diagnostics(result_dir, source_dir, args)
        dec = decision(result_dir, source_dir, args, behavior)
        plots(result_dir, source_dir, behavior)
        files = collect_files(result_dir)
        write_text(result_dir / COMPLETE_FLAG, "terminal_decision = phase_n3pf_ms_seed2_ab_audit_rerun_complete\n")
        write_text(result_dir / "phase_n3pf_ms_seed2_ab_status.txt", "complete\n")
        write_text(result_dir / "PHASE_N3PF_MS_SEED2_AB_AUDIT_RERUN_REPORT.md", report(result_dir, source_dir, dec, behavior, files))
        print("terminal_decision = phase_n3pf_ms_seed2_ab_audit_rerun_complete", flush=True)
    except AnalysisStop as exc:
        write_stop(result_dir, exc.reason, exc.detail)
        raise SystemExit(2) from exc
    except Exception:
        write_stop(result_dir, "diagnostics_failed", traceback.format_exc())
        raise SystemExit(2)


if __name__ == "__main__":
    main()
