from __future__ import annotations

import argparse
import csv
import json
import os
import random
import shutil
import socket
import sys
import time
import traceback
from pathlib import Path
from typing import Any

import numpy as np
import torch
import yaml
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import scripts.train_env_v2_gpsi_ppo_n3z2c as base_train


RESULT_DIR = ROOT / "results/env_v2_phase_n3z2c_audit"
STOP_FLAGS = {
    "phase_n3fz_missing": "PHASE_N3Z2C_AUDIT_STOP_N3Z2C_MISSING.flag",
    "phase_n3_5_missing": "PHASE_N3Z2C_AUDIT_STOP_N3Z2C_MISSING.flag",
    "gpsi_checkpoint_missing": "PHASE_N3Z2C_AUDIT_STOP_CORRECTED_PARENT_MISSING.flag",
    "z2_parent_missing": "PHASE_N3Z2C_AUDIT_STOP_CORRECTED_PARENT_MISSING.flag",
    "z_stats_missing": "PHASE_N3Z2C_AUDIT_STOP_CORRECTED_PARENT_MISSING.flag",
    "gpsi_wrapper_failed": "PHASE_N3Z2C_AUDIT_STOP_DIAGNOSTICS_FAILED.flag",
    "gpsi_not_frozen": "PHASE_N3Z2C_AUDIT_STOP_DIAGNOSTICS_FAILED.flag",
    "schema_mismatch": "PHASE_N3Z2C_AUDIT_STOP_RESUME_SEMANTICS_UNRESOLVED.flag",
    "output_scale_invalid": "PHASE_N3Z2C_AUDIT_STOP_DIAGNOSTICS_FAILED.flag",
    "train_failed": "PHASE_N3Z2C_AUDIT_STOP_TRAIN_FAILED.flag",
}


class AuditTrainStop(Exception):
    def __init__(self, reason: str, detail: str) -> None:
        super().__init__(detail)
        self.reason = reason
        self.detail = detail


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train Phase N3Z2C-Audit corrected short continuation.")
    parser.add_argument("--config", required=True)
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--resume", required=True)
    parser.add_argument("--additional-steps", type=int, default=250_000)
    parser.add_argument("--target-total-steps", type=int, default=750_000)
    parser.add_argument("--parent-total-steps", type=int, default=500_000)
    parser.add_argument("--checkpoint-total-steps", nargs="*", type=int, default=[750_000])
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--n-envs", type=int, default=None)
    parser.add_argument("--device", type=str, default=None)
    parser.add_argument("--heartbeat-seconds", type=float, default=300.0)
    return parser.parse_args()


def rel(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fields: list[str] = []
    seen: set[str] = set()
    for row in rows:
        for key in row:
            if key not in seen:
                fields.append(key)
                seen.add(key)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def append_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    old: list[dict[str, Any]] = []
    if path.exists() and path.stat().st_size > 0:
        with path.open("r", newline="", encoding="utf-8") as handle:
            old = list(csv.DictReader(handle))
    write_csv(path, old + rows)


def ensure_dirs(out_dir: Path) -> None:
    for path in [out_dir, RESULT_DIR, RESULT_DIR / "logs", RESULT_DIR / "tables", RESULT_DIR / "plots"]:
        path.mkdir(parents=True, exist_ok=True)


def write_stop(reason: str, detail: str) -> None:
    ensure_dirs(RESULT_DIR)
    flag = STOP_FLAGS.get(reason, STOP_FLAGS["train_failed"])
    write_text(RESULT_DIR / flag, f"{reason}\n{detail.strip()}\n")
    write_text(RESULT_DIR / "phase_n3z2c_audit_status.txt", f"stopped:{flag}\n")
    write_text(
        RESULT_DIR / "PHASE_N3Z2C_AUDIT_REPORT.md",
        "\n".join(
            [
                "# Phase N3Z2C-Audit Report",
                "",
                f"`terminal_decision = phase_n3z2c_audit_stopped_{reason}`",
                "",
                "Partial report generated by corrected short continuation training.",
                "",
                "```text",
                detail.strip(),
                "```",
                "",
                "Can enter N4: no.",
            ]
        )
        + "\n",
    )


def load_config(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        payload = yaml.safe_load(handle)
    if not isinstance(payload, dict):
        raise AuditTrainStop("schema_mismatch", f"config is not a mapping: {rel(path)}")
    return payload


def save_yaml(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def patch_base_result_dir() -> None:
    base_train.RESULT_DIR = RESULT_DIR
    base_train.STOP_FLAGS = STOP_FLAGS


def write_command_manifest(args: argparse.Namespace, cfg: dict[str, Any], out_dir: Path) -> None:
    checkpoint = ROOT / str(cfg.get("gpsi", {}).get("checkpoint", "work_dirs/gpsi_heada_v1_nll/best.pth"))
    row = {
        "stage": "train_corrected_short_continuation",
        "method_key": cfg.get("method_key", ""),
        "method": cfg.get("method_name", cfg.get("method_key", "")),
        "command": " ".join(["python", *sys.argv]),
        "config": rel(ROOT / args.config),
        "gpsi_checkpoint": rel(checkpoint),
        "gpsi_checkpoint_sha256": base_train.sha256(checkpoint) if checkpoint.exists() else "missing",
        "out_dir": rel(out_dir),
        "resume": rel(ROOT / args.resume),
        "parent_total_steps": int(args.parent_total_steps),
        "additional_steps": int(args.additional_steps),
        "target_total_steps": int(args.target_total_steps),
        "checkpoint_total_steps": json.dumps([int(step) for step in args.checkpoint_total_steps]),
        "seed": int(args.seed),
        "n_envs": int(args.n_envs or cfg.get("env", {}).get("n_envs", 4)),
        "device": args.device or str(cfg.get("env", {}).get("device", "cpu")),
        "reset_num_timesteps": False,
    }
    append_csv(RESULT_DIR / "tables/phase_n3z2c_audit_command_manifest.csv", [row])


def schedule_value(schedule: Any, progress_remaining: float) -> Any:
    try:
        return float(schedule(progress_remaining)) if callable(schedule) else float(schedule)
    except Exception as exc:
        return f"unavailable:{type(exc).__name__}:{exc}"


def train() -> None:
    args = parse_args()
    out_dir = ROOT / args.out_dir
    ensure_dirs(out_dir)
    patch_base_result_dir()
    try:
        cfg = load_config(ROOT / args.config)
        if args.n_envs is not None:
            cfg.setdefault("env", {})["n_envs"] = int(args.n_envs)
        if args.device is not None:
            cfg.setdefault("env", {})["device"] = args.device
        cfg.setdefault("training", {})["seed"] = int(args.seed)
        cfg["training"]["parent_total_steps"] = int(args.parent_total_steps)
        cfg["training"]["additional_steps"] = int(args.additional_steps)
        cfg["training"]["total_steps"] = int(args.target_total_steps)
        cfg["training"]["checkpoint_steps"] = [int(step) for step in args.checkpoint_total_steps]
        cfg["training"]["resume"] = rel(ROOT / args.resume)
        cfg["training"]["reset_num_timesteps"] = False

        base_train.check_prerequisites(cfg, args)
        guard_action = base_train.prepare_training_guard(out_dir, cfg, args)
        if guard_action in {"skip", "wait"}:
            return
        save_yaml(out_dir / "config_resolved.yaml", cfg)
        write_command_manifest(args, cfg, out_dir)
        set_seed(args.seed)
        base_train.validate_wrapper(cfg, args, out_dir)

        n_envs = int(cfg.get("env", {}).get("n_envs", 4))
        device = args.device or str(cfg.get("env", {}).get("device", "cpu"))
        env_fns = [base_train.make_env_factory(cfg, args, rank) for rank in range(n_envs)]
        vec_env = DummyVecEnv(env_fns)
        ppo_cfg = cfg.get("ppo", {})
        method_key = str(cfg.get("method_key", Path(args.config).stem))
        method_name = str(cfg.get("method_name", method_key))
        print(
            f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] N3Z2C_AUDIT_TRAIN_CONFIG "
            f"config={method_key} parent_total_steps={args.parent_total_steps} additional_steps={args.additional_steps} "
            f"target_total_steps={args.target_total_steps} seed={args.seed} n_envs={n_envs} device={device} "
            f"resume={rel(ROOT / args.resume)} out_dir={rel(out_dir)} reset_num_timesteps=false",
            flush=True,
        )

        model = PPO.load(
            str(ROOT / args.resume),
            env=vec_env,
            device=device,
            seed=int(args.seed),
            tensorboard_log=str(out_dir / "tensorboard"),
        )
        model.verbose = 1
        loaded_hparams = {
            "n_steps": int(model.n_steps),
            "batch_size": int(model.batch_size),
            "n_epochs": int(model.n_epochs),
            "gamma": float(model.gamma),
            "gae_lambda": float(model.gae_lambda),
            "ent_coef": float(model.ent_coef),
            "vf_coef": float(model.vf_coef),
            "max_grad_norm": float(model.max_grad_norm),
        }
        expected_hparams = {
            "n_steps": int(ppo_cfg.get("n_steps", loaded_hparams["n_steps"])),
            "batch_size": int(ppo_cfg.get("batch_size", loaded_hparams["batch_size"])),
            "n_epochs": int(ppo_cfg.get("n_epochs", loaded_hparams["n_epochs"])),
            "gamma": float(ppo_cfg.get("gamma", loaded_hparams["gamma"])),
            "gae_lambda": float(ppo_cfg.get("gae_lambda", loaded_hparams["gae_lambda"])),
            "ent_coef": float(ppo_cfg.get("ent_coef", loaded_hparams["ent_coef"])),
            "vf_coef": float(ppo_cfg.get("vf_coef", loaded_hparams["vf_coef"])),
            "max_grad_norm": float(ppo_cfg.get("max_grad_norm", loaded_hparams["max_grad_norm"])),
        }
        mismatched = {key: {"loaded": loaded_hparams[key], "config": expected_hparams[key]} for key in loaded_hparams if loaded_hparams[key] != expected_hparams[key]}
        if mismatched:
            raise AuditTrainStop("schema_mismatch", f"loaded PPO hyperparameters differ from config: {json.dumps(mismatched, sort_keys=True)}")

        optimizer_state = model.policy.optimizer.state_dict()
        before_steps = int(model.num_timesteps)
        progress_before = 1.0 - (float(before_steps) / max(float(args.target_total_steps), 1.0))
        resume_row = {
            "phase": "before_learn",
            "loaded_checkpoint_path": rel(ROOT / args.resume),
            "parent_total_steps": int(args.parent_total_steps),
            "additional_steps": int(args.additional_steps),
            "target_total_steps": int(args.target_total_steps),
            "reset_num_timesteps": False,
            "model_num_timesteps": before_steps,
            "model_expected_parent_steps": int(args.parent_total_steps),
            "model_parent_step_match": int(before_steps == int(args.parent_total_steps)),
            "optimizer_state_entries": int(len(optimizer_state.get("state", {}))),
            "optimizer_state_restored": int(bool(optimizer_state.get("state"))),
            "learning_rate_current": schedule_value(model.lr_schedule, progress_before),
            "clip_range_current": schedule_value(model.clip_range, progress_before),
            "progress_remaining_assuming_global_total": float(progress_before),
            "n_envs": int(n_envs),
            "n_steps": int(model.n_steps),
            "batch_size": int(model.batch_size),
            "obs_dim": int(vec_env.observation_space["obs"].shape[-1]),
            "hostname": socket.gethostname(),
        }
        append_csv(RESULT_DIR / "tables/phase_n3z2c_audit_resume_semantics.csv", [resume_row])

        callback = base_train.N3Z2CTrainCallback(
            args.additional_steps,
            args.target_total_steps,
            args.parent_total_steps,
            method_key,
            method_name,
            args.heartbeat_seconds,
        )
        targets = [step for step in args.checkpoint_total_steps if args.parent_total_steps < step <= args.target_total_steps]
        checkpoint_cb = base_train.TotalStepCheckpointCallback(targets, out_dir, args.parent_total_steps)
        model.learn(
            total_timesteps=int(args.additional_steps),
            callback=[callback, checkpoint_cb],
            progress_bar=False,
            reset_num_timesteps=False,
        )
        final_path = out_dir / "final.zip"
        model.save(str(final_path))
        final_step_checkpoint = out_dir / f"checkpoint_{int(args.target_total_steps) // 1000}k.zip"
        if not final_step_checkpoint.exists():
            shutil.copyfile(final_path, final_step_checkpoint)
        if not (out_dir / "best_by_eval.zip").exists():
            shutil.copyfile(final_path, out_dir / "best_by_eval.zip")
        append_csv(RESULT_DIR / "tables/phase_n3z2c_audit_short_continuation_train_curve.csv", callback.episode_rows)
        append_csv(RESULT_DIR / "tables/phase_n3z2c_audit_short_continuation_heartbeat.csv", callback.heartbeat_rows)
        after_steps = int(model.num_timesteps)
        progress_after = 1.0 - (float(after_steps) / max(float(args.target_total_steps), 1.0))
        append_csv(
            RESULT_DIR / "tables/phase_n3z2c_audit_resume_semantics.csv",
            [
                {
                    "phase": "after_learn",
                    "loaded_checkpoint_path": rel(ROOT / args.resume),
                    "parent_total_steps": int(args.parent_total_steps),
                    "additional_steps": int(args.additional_steps),
                    "target_total_steps": int(args.target_total_steps),
                    "reset_num_timesteps": False,
                    "model_num_timesteps": after_steps,
                    "model_expected_target_steps": int(args.target_total_steps),
                    "model_target_step_match": int(after_steps >= int(args.target_total_steps)),
                    "optimizer_state_entries": int(len(model.policy.optimizer.state_dict().get("state", {}))),
                    "optimizer_state_restored": int(bool(model.policy.optimizer.state_dict().get("state"))),
                    "learning_rate_current": schedule_value(model.lr_schedule, progress_after),
                    "clip_range_current": schedule_value(model.clip_range, progress_after),
                    "progress_remaining_assuming_global_total": float(progress_after),
                    "n_envs": int(n_envs),
                    "n_steps": int(model.n_steps),
                    "batch_size": int(model.batch_size),
                    "obs_dim": int(vec_env.observation_space["obs"].shape[-1]),
                    "hostname": socket.gethostname(),
                }
            ],
        )
        vec_env.close()
        base_train.complete_path(out_dir).write_text(
            f"completed\nparent_total_steps={int(args.parent_total_steps)}\n"
            f"additional_steps={int(args.additional_steps)}\n"
            f"target_total_steps={int(args.target_total_steps)}\n"
            "reset_num_timesteps=false\n",
            encoding="utf-8",
        )
        base_train.write_train_status(out_dir, "completed", cfg, args, "corrected short continuation completed successfully")
        base_train.lock_path(out_dir).unlink(missing_ok=True)
        print(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] N3Z2C_AUDIT_TRAIN_END config={method_key} final={rel(final_path)}", flush=True)
    except base_train.PhaseN3Z2CTrainStop as exc:
        write_stop(exc.reason, exc.detail)
        raise SystemExit(2) from exc
    except AuditTrainStop as exc:
        write_stop(exc.reason, exc.detail)
        raise SystemExit(2) from exc
    except Exception:
        detail = traceback.format_exc()
        write_stop("train_failed", detail)
        raise SystemExit(2)


if __name__ == "__main__":
    train()
