from __future__ import annotations

import argparse
import csv
import json
import os
import random
import shutil
import socket
import subprocess
import sys
import time
import traceback
from pathlib import Path
from typing import Any

import numpy as np
import torch
import yaml
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import scripts.train_env_v2_gpsi_ppo_n3fz as base_train
import scripts.train_env_v2_gpsi_ppo_n3p as n3p_train


RESULT_DIR = ROOT / "results/env_v2_phase_n3pf_ms_multiseed"
N3PFV_FLAG = ROOT / "results/env_v2_phase_n3pfv_checkpoint_verification/PHASE_N3PFV_CHECKPOINT_VERIFICATION_COMPLETE.flag"
N3P_FLAG = ROOT / "results/env_v2_phase_n3p_noz_representation_ablation/PHASE_N3P_NOZ_REPRESENTATION_ABLATION_COMPLETE.flag"
N35_FLAG = ROOT / "results/env_v2_phase_n3_5_gpsi_wrapper_audit/PHASE_N3_5_GPSI_WRAPPER_AUDIT_COMPLETE.flag"

STOP_FLAGS = {
    "config_mismatch": "PHASE_N3PF_MS_STOP_CONFIG_MISMATCH.flag",
    "gpsi_checkpoint_missing": "PHASE_N3PF_MS_STOP_GPSI_CHECKPOINT_MISSING.flag",
    "train_failed": "PHASE_N3PF_MS_STOP_TRAIN_FAILED.flag",
    "diagnostics_failed": "PHASE_N3PF_MS_STOP_DIAGNOSTICS_FAILED.flag",
}


class N3PFMSTrainStop(Exception):
    def __init__(self, reason: str, detail: str) -> None:
        super().__init__(detail)
        self.reason = reason
        self.detail = detail


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train Phase N3PF-MS P3 block-projected seeds.")
    parser.add_argument("--config", required=True)
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--train-steps", type=int, default=1_500_000)
    parser.add_argument("--checkpoint-steps", nargs="*", type=int, default=[250_000, 500_000, 750_000, 1_000_000, 1_250_000, 1_500_000])
    parser.add_argument("--seed", type=int, required=True)
    parser.add_argument("--n-envs", type=int, default=4)
    parser.add_argument("--device", default="cpu")
    parser.add_argument("--heartbeat-seconds", type=float, default=300.0)
    parser.add_argument("--validate-only", action="store_true")
    return parser.parse_args()


def rel(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fields: list[str] = []
    seen: set[str] = set()
    for row in rows:
        for key in row:
            if key not in seen:
                fields.append(key)
                seen.add(key)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def append_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    old: list[dict[str, Any]] = []
    if path.exists() and path.stat().st_size > 0:
        with path.open("r", newline="", encoding="utf-8") as handle:
            old = list(csv.DictReader(handle))
    write_csv(path, old + rows)


def ensure_dirs(out_dir: Path) -> None:
    for path in [out_dir, RESULT_DIR, RESULT_DIR / "logs", RESULT_DIR / "tables", RESULT_DIR / "plots"]:
        path.mkdir(parents=True, exist_ok=True)


def write_stop(reason: str, detail: str) -> None:
    RESULT_DIR.mkdir(parents=True, exist_ok=True)
    flag = STOP_FLAGS.get(reason, STOP_FLAGS["train_failed"])
    write_text(RESULT_DIR / flag, f"{reason}\n{detail.strip()}\n")
    write_text(RESULT_DIR / "phase_n3pf_ms_status.txt", f"stopped:{flag}\n")
    write_text(
        RESULT_DIR / "PHASE_N3PF_MS_MULTI_SEED_REPORT.md",
        "\n".join(
            [
                "# Phase N3PF-MS Multi-Training-Seed Report",
                "",
                f"`terminal_decision = phase_n3pf_ms_stopped_{reason}`",
                "",
                "Partial report generated by training script.",
                "",
                "```text",
                detail.strip(),
                "```",
            ]
        )
        + "\n",
    )


def load_config(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        payload = yaml.safe_load(handle)
    if not isinstance(payload, dict):
        raise N3PFMSTrainStop("config_mismatch", f"config is not a mapping: {rel(path)}")
    return payload


def save_yaml(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")


def sha256(path: Path) -> str:
    return base_train.sha256(path)


def run_command(label: str, command: list[str]) -> dict[str, Any]:
    try:
        proc = subprocess.run(command, check=False, text=True, capture_output=True, timeout=30)
        return {"item": label, "command": " ".join(command), "returncode": int(proc.returncode), "output": (proc.stdout + proc.stderr).strip()}
    except Exception as exc:
        return {"item": label, "command": " ".join(command), "returncode": -1, "output": f"{type(exc).__name__}: {exc}"}


def write_resource_affinity(stage: str, seed: int) -> None:
    rows = [
        run_command("nproc", ["nproc"]),
        run_command("nproc_all", ["nproc", "--all"]),
        run_command("taskset_current_process", ["taskset", "-pc", str(os.getpid())]),
        run_command("lscpu", ["lscpu"]),
        run_command("free_h", ["free", "-h"]),
        run_command("df_root", ["df", "-h", "/"]),
        run_command("nvidia_smi", ["nvidia-smi"]),
    ]
    for path in ["/sys/fs/cgroup/cpuset.cpus.effective", "/sys/fs/cgroup/cpu.max"]:
        p = Path(path)
        rows.append({"item": p.name, "command": f"read {path}", "returncode": 0 if p.exists() else 1, "output": p.read_text().strip() if p.exists() else "missing"})
    rows.append(
        {
            "item": "python_cpu_affinity",
            "command": "python runtime",
            "returncode": 0,
            "output": json.dumps(
                {
                    "os_cpu_count": os.cpu_count(),
                    "sched_affinity_count": len(os.sched_getaffinity(0)) if hasattr(os, "sched_getaffinity") else None,
                    "sched_affinity": sorted(os.sched_getaffinity(0)) if hasattr(os, "sched_getaffinity") else None,
                    "OMP_NUM_THREADS": os.environ.get("OMP_NUM_THREADS", ""),
                    "MKL_NUM_THREADS": os.environ.get("MKL_NUM_THREADS", ""),
                    "OPENBLAS_NUM_THREADS": os.environ.get("OPENBLAS_NUM_THREADS", ""),
                    "NUMEXPR_NUM_THREADS": os.environ.get("NUMEXPR_NUM_THREADS", ""),
                    "CUDA_VISIBLE_DEVICES": os.environ.get("CUDA_VISIBLE_DEVICES", ""),
                },
                sort_keys=True,
            ),
        }
    )
    for row in rows:
        row["stage"] = stage
        row["training_seed"] = int(seed)
        row["timestamp"] = time.strftime("%Y-%m-%d %H:%M:%S")
    append_csv(RESULT_DIR / "tables/phase_n3pf_ms_resource_affinity.csv", rows)


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def validate_config(cfg: dict[str, Any], args: argparse.Namespace) -> None:
    missing_flags = [path for path in [N35_FLAG, N3P_FLAG, N3PFV_FLAG] if not path.exists()]
    if missing_flags:
        raise N3PFMSTrainStop("config_mismatch", "missing prerequisite flags: " + ", ".join(rel(path) for path in missing_flags))
    cfg["method_key"] = "block_projected"
    cfg["method_name"] = f"n3pf_ms_block_projected_seed{int(args.seed)}"
    cfg.setdefault("env", {})["n_envs"] = int(args.n_envs)
    cfg.setdefault("env", {})["device"] = str(args.device)
    cfg.setdefault("training", {})["seed"] = int(args.seed)
    cfg["training"]["total_steps"] = int(args.train_steps)
    cfg["training"]["checkpoint_steps"] = [int(step) for step in args.checkpoint_steps]
    cfg["training"].pop("parent_total_steps", None)
    cfg["training"].pop("additional_steps", None)
    cfg["training"].pop("resume", None)
    cfg["training"].pop("reset_num_timesteps", None)
    cfg["training"]["no_shield"] = True
    cfg["training"]["action_filtering"] = False
    cfg["training"]["use_safety_cost"] = False
    n3p_train.validate_config_semantics(cfg)
    if int(args.train_steps) != 1_500_000:
        raise N3PFMSTrainStop("config_mismatch", f"N3PF-MS train_steps must be 1500000, got {args.train_steps}")
    required_steps = {250_000, 500_000, 750_000, 1_000_000, 1_250_000, 1_500_000}
    if set(int(step) for step in args.checkpoint_steps) != required_steps:
        raise N3PFMSTrainStop("config_mismatch", f"checkpoint steps must be {sorted(required_steps)}")
    if int(args.n_envs) != 4 or str(args.device) != "cpu":
        raise N3PFMSTrainStop("config_mismatch", f"N3PF-MS requires n_envs=4 and device=cpu, got n_envs={args.n_envs} device={args.device}")
    checkpoint = ROOT / str(cfg.get("gpsi", {}).get("checkpoint", "work_dirs/gpsi_heada_v1_nll/best.pth"))
    if not checkpoint.exists():
        raise N3PFMSTrainStop("gpsi_checkpoint_missing", f"missing Gpsi checkpoint: {rel(checkpoint)}")


def validate_wrapper(cfg: dict[str, Any], args: argparse.Namespace) -> None:
    env = n3p_train.make_wrapper(cfg, "eval_flow_id", args.device)
    try:
        obs, _info = env.reset(seed=int(args.seed))
        freeze = env.freeze_check
        expected_dim = int(cfg.get("gpsi", {}).get("obs_aug_dim", 30))
        actual_dim = int(obs["obs"].shape[-1])
        rows = [
            {"training_seed": int(args.seed), "check": "gpsi_frozen", "value": int(not freeze.training and not freeze.requires_grad_any and freeze.trainable_parameters == 0), "detail": json.dumps(freeze.__dict__, sort_keys=True)},
            {"training_seed": int(args.seed), "check": "aug_obs_dim", "value": actual_dim, "detail": f"expected={expected_dim}"},
            {"training_seed": int(args.seed), "check": "include_z", "value": int(bool(env.latest_gpsi_debug.get("include_z", False))), "detail": "must be 0"},
            {"training_seed": int(args.seed), "check": "feature_adapter", "value": str(cfg.get("ppo", {}).get("feature_adapter", "")), "detail": "must be block_projected_no_z"},
            {"training_seed": int(args.seed), "check": "no_shield", "value": 1, "detail": "training script raw PPO action only"},
            {"training_seed": int(args.seed), "check": "no_action_filtering", "value": 1, "detail": "training script raw PPO action only"},
            {"training_seed": int(args.seed), "check": "no_safety_cost", "value": 1, "detail": "EnvV2 original reward"},
        ]
        append_csv(RESULT_DIR / "tables/phase_n3pf_ms_schema_check.csv", rows)
        if freeze.training or freeze.requires_grad_any or freeze.trainable_parameters != 0:
            raise N3PFMSTrainStop("config_mismatch", f"Gpsi freeze check failed: {freeze}")
        if actual_dim != expected_dim:
            raise N3PFMSTrainStop("config_mismatch", f"aug obs dim mismatch: {actual_dim} vs {expected_dim}")
        if bool(env.latest_gpsi_debug.get("include_z", False)):
            raise N3PFMSTrainStop("config_mismatch", "include_z must be false")
    finally:
        env.close()


def write_config_manifest(cfg: dict[str, Any], args: argparse.Namespace, out_dir: Path, adapter_count: int) -> None:
    gpsi = cfg.get("gpsi", {})
    ppo = cfg.get("ppo", {})
    append_csv(
        RESULT_DIR / "tables/phase_n3pf_ms_config_manifest.csv",
        [
            {
                "training_seed": int(args.seed),
                "method_key": "block_projected",
                "method": cfg.get("method_name", ""),
                "config": rel(ROOT / args.config),
                "out_dir": rel(out_dir),
                "obs_aug_dim": int(gpsi.get("obs_aug_dim", -1)),
                "include_z": int(bool(gpsi.get("include_z", False))),
                "include_logvar": int(bool(gpsi.get("include_logvar", True))),
                "logvar_output_scale": float(gpsi.get("logvar_output_scale", 1.0)),
                "feature_adapter": str(ppo.get("feature_adapter", "")),
                "adapter_parameter_count": int(adapter_count),
                "train_steps": int(args.train_steps),
                "checkpoint_steps": json.dumps([int(step) for step in args.checkpoint_steps]),
                "n_envs": int(args.n_envs),
                "device": args.device,
                "no_shield": 1,
                "action_filtering": 0,
                "use_safety_cost": 0,
            }
        ],
    )


def write_command_manifest(args: argparse.Namespace, cfg: dict[str, Any], out_dir: Path) -> None:
    checkpoint = ROOT / str(cfg.get("gpsi", {}).get("checkpoint", "work_dirs/gpsi_heada_v1_nll/best.pth"))
    append_csv(
        RESULT_DIR / "tables/phase_n3pf_ms_command_manifest.csv",
        [
            {
                "stage": "train",
                "training_seed": int(args.seed),
                "command": " ".join(["python", *sys.argv]),
                "config": rel(ROOT / args.config),
                "gpsi_checkpoint": rel(checkpoint),
                "gpsi_checkpoint_sha256": sha256(checkpoint) if checkpoint.exists() else "missing",
                "out_dir": rel(out_dir),
                "train_steps": int(args.train_steps),
                "checkpoint_steps": json.dumps([int(step) for step in args.checkpoint_steps]),
                "n_envs": int(args.n_envs),
                "device": args.device,
            }
        ],
    )


def train() -> None:
    args = parse_args()
    out_dir = ROOT / args.out_dir
    ensure_dirs(out_dir)
    try:
        cfg = load_config(ROOT / args.config)
        validate_config(cfg, args)
        if args.validate_only:
            write_resource_affinity("validate_only", int(args.seed))
            validate_wrapper(cfg, args)
            print(
                f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] N3PF_MS_VALIDATE_OK "
                f"seed={args.seed} config={rel(ROOT / args.config)} n_envs={args.n_envs} device={args.device}",
                flush=True,
            )
            return
        action = base_train.prepare_training_guard(out_dir, cfg, args)
        if action in {"skip", "wait"}:
            return
        save_yaml(out_dir / "config_resolved.yaml", cfg)
        write_resource_affinity("train_preflight", int(args.seed))
        write_command_manifest(args, cfg, out_dir)
        set_seed(int(args.seed))
        validate_wrapper(cfg, args)

        env_fns = [n3p_train.make_env_factory(cfg, args, rank) for rank in range(int(args.n_envs))]
        vec_env = DummyVecEnv(env_fns)
        ppo_cfg = cfg.get("ppo", {})
        method_key = f"block_projected_s{int(args.seed)}"
        method_name = str(cfg.get("method_name", method_key))
        print(
            f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] N3PF_MS_TRAIN_CONFIG "
            f"seed={args.seed} steps={args.train_steps} n_envs={args.n_envs} device={args.device} "
            f"out_dir={rel(out_dir)} no_shield=true",
            flush=True,
        )
        model = PPO(
            "MultiInputPolicy",
            vec_env,
            seed=int(args.seed),
            device=args.device,
            verbose=1,
            tensorboard_log=str(out_dir / "tensorboard"),
            policy_kwargs=n3p_train.make_policy_kwargs(cfg),
            n_steps=int(ppo_cfg.get("n_steps", 1024)),
            batch_size=int(ppo_cfg.get("batch_size", 256)),
            n_epochs=int(ppo_cfg.get("n_epochs", 10)),
            learning_rate=float(ppo_cfg.get("learning_rate", 3e-4)),
            gamma=float(ppo_cfg.get("gamma", 0.99)),
            gae_lambda=float(ppo_cfg.get("gae_lambda", 0.95)),
            clip_range=float(ppo_cfg.get("clip_range", 0.2)),
            ent_coef=float(ppo_cfg.get("ent_coef", 0.01)),
            vf_coef=float(ppo_cfg.get("vf_coef", 0.5)),
            max_grad_norm=float(ppo_cfg.get("max_grad_norm", 0.5)),
        )
        write_config_manifest(cfg, args, out_dir, n3p_train.adapter_parameter_count(model))
        callback = base_train.N3FZTrainCallback(int(args.train_steps), method_key, method_name, float(args.heartbeat_seconds))
        checkpoint_cb = base_train.FixedNameCheckpointCallback([int(step) for step in args.checkpoint_steps], out_dir)
        model.learn(total_timesteps=int(args.train_steps), callback=[callback, checkpoint_cb], progress_bar=False, reset_num_timesteps=True)
        final_path = out_dir / "final.zip"
        model.save(str(final_path))
        final_step_checkpoint = out_dir / f"checkpoint_{int(args.train_steps) // 1000}k.zip"
        if not final_step_checkpoint.exists():
            shutil.copyfile(final_path, final_step_checkpoint)
        episode_rows = [dict(row, training_seed=int(args.seed)) for row in callback.episode_rows]
        heartbeat_rows = [dict(row, training_seed=int(args.seed)) for row in callback.heartbeat_rows]
        append_csv(RESULT_DIR / "tables/phase_n3pf_ms_train_curve.csv", episode_rows)
        append_csv(RESULT_DIR / "tables/phase_n3pf_ms_train_heartbeat.csv", heartbeat_rows)
        vec_env.close()
        base_train.complete_path(out_dir).write_text(f"completed\ntrain_steps={int(args.train_steps)}\ntraining_seed={int(args.seed)}\n", encoding="utf-8")
        base_train.write_train_status(out_dir, "completed", cfg, args, "training completed successfully")
        base_train.lock_path(out_dir).unlink(missing_ok=True)
        print(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] N3PF_MS_TRAIN_END seed={args.seed} final={rel(final_path)}", flush=True)
    except N3PFMSTrainStop as exc:
        write_stop(exc.reason, exc.detail)
        raise SystemExit(2) from exc
    except base_train.PhaseN3FZTrainStop as exc:
        write_stop("train_failed", exc.detail)
        raise SystemExit(2) from exc
    except Exception:
        detail = traceback.format_exc()
        try:
            if "cfg" in locals():
                base_train.write_train_status(out_dir, "failed", cfg, args, detail)
            base_train.lock_path(out_dir).unlink(missing_ok=True)
        except Exception:
            pass
        write_stop("train_failed", detail)
        raise SystemExit(2)


if __name__ == "__main__":
    train()
