from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import random
import shutil
import socket
import subprocess
import sys
import time
import traceback
from pathlib import Path
from typing import Any

import numpy as np
import torch
import yaml
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import scripts.train_env_v2_gpsi_ppo_n3fz as base_train
import scripts.train_env_v2_gpsi_ppo_n3p as n3p_train


RESULT_DIR = ROOT / "results/env_v2_phase_n3pf_ms_seed2_ab_audit_rerun"
STEP_B_DIR = RESULT_DIR / "step_b_rerun"
N3PF_MS_FLAG = ROOT / "results/env_v2_phase_n3pf_ms_multiseed/PHASE_N3PF_MS_MULTI_SEED_COMPLETE.flag"

STOP_FLAGS = {
    "config_mismatch": "PHASE_N3PF_MS_AB_STOP_CONFIG_MISMATCH.flag",
    "gpsi_checkpoint_missing": "PHASE_N3PF_MS_AB_STOP_FEATURE_GPSI_DIAGNOSTICS_FAILED.flag",
    "train_failed": "PHASE_N3PF_MS_AB_STOP_TRAIN_FAILED.flag",
    "resource_unsafe": "PHASE_N3PF_MS_AB_STOP_RESOURCE_UNSAFE.flag",
}

CHECKPOINT_STEPS = [250_000, 500_000, 750_000, 1_000_000, 1_250_000, 1_500_000]


class Seed2ABTrainStop(Exception):
    def __init__(self, reason: str, detail: str) -> None:
        super().__init__(detail)
        self.reason = reason
        self.detail = detail


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Phase N3PF-MS-AB Step B P3 seed rerun training.")
    parser.add_argument("--config", default="configs/env_v2_gpsi_heada_ppo_n3pf_block_projected.yaml")
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--run-name", choices=["seed2_rerunA", "seed3_sanity"], required=True)
    parser.add_argument("--train-steps", type=int, default=1_500_000)
    parser.add_argument("--checkpoint-steps", nargs="*", type=int, default=CHECKPOINT_STEPS)
    parser.add_argument("--seed", type=int, required=True)
    parser.add_argument("--n-envs", type=int, default=4)
    parser.add_argument("--device", default="cpu")
    parser.add_argument("--heartbeat-seconds", type=float, default=300.0)
    parser.add_argument("--validate-only", action="store_true")
    return parser.parse_args()


def rel(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


def ensure_dirs(out_dir: Path) -> None:
    for path in [out_dir, RESULT_DIR, STEP_B_DIR, STEP_B_DIR / "logs", STEP_B_DIR / "tables", STEP_B_DIR / "plots"]:
        path.mkdir(parents=True, exist_ok=True)


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fields: list[str] = []
    seen: set[str] = set()
    for row in rows:
        for key in row:
            if key not in seen:
                fields.append(key)
                seen.add(key)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def append_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    old: list[dict[str, Any]] = []
    if path.exists() and path.stat().st_size > 0:
        with path.open("r", newline="", encoding="utf-8") as handle:
            old = list(csv.DictReader(handle))
    write_csv(path, old + rows)


def write_stop(reason: str, detail: str) -> None:
    RESULT_DIR.mkdir(parents=True, exist_ok=True)
    flag = STOP_FLAGS.get(reason, STOP_FLAGS["train_failed"])
    write_text(RESULT_DIR / flag, f"{reason}\n{detail.strip()}\n")
    write_text(RESULT_DIR / "phase_n3pf_ms_seed2_ab_status.txt", f"stopped:{flag}\n")
    write_text(
        RESULT_DIR / "PHASE_N3PF_MS_SEED2_AB_AUDIT_RERUN_REPORT.md",
        "\n".join(
            [
                "# Phase N3PF-MS-AB Seed2 Collapse Audit + Minimal Rerun Sanity",
                "",
                f"`terminal_decision = phase_n3pf_ms_seed2_ab_stopped_{reason}`",
                "",
                "Partial report generated by Step B training.",
                "",
                "```text",
                detail.strip(),
                "```",
            ]
        )
        + "\n",
    )


def load_config(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        payload = yaml.safe_load(handle)
    if not isinstance(payload, dict):
        raise Seed2ABTrainStop("config_mismatch", f"config is not a mapping: {rel(path)}")
    return payload


def save_yaml(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def run_command(label: str, command: list[str]) -> dict[str, Any]:
    try:
        proc = subprocess.run(command, check=False, text=True, capture_output=True, timeout=30)
        return {"item": label, "command": " ".join(command), "returncode": int(proc.returncode), "output": (proc.stdout + proc.stderr).strip()}
    except Exception as exc:
        return {"item": label, "command": " ".join(command), "returncode": -1, "output": f"{type(exc).__name__}: {exc}"}


def write_resource_affinity(stage: str, args: argparse.Namespace) -> None:
    rows = [
        run_command("nproc", ["nproc"]),
        run_command("nproc_all", ["nproc", "--all"]),
        run_command("taskset_current_process", ["taskset", "-pc", str(os.getpid())]),
        run_command("lscpu", ["lscpu"]),
        run_command("free_h", ["free", "-h"]),
        run_command("df_root", ["df", "-h", "/"]),
        run_command("nvidia_smi", ["nvidia-smi"]),
    ]
    for path in ["/sys/fs/cgroup/cpuset.cpus.effective", "/sys/fs/cgroup/cpu.max"]:
        p = Path(path)
        rows.append({"item": p.name, "command": f"read {path}", "returncode": 0 if p.exists() else 1, "output": p.read_text().strip() if p.exists() else "missing"})
    rows.append(
        {
            "item": "python_cpu_affinity",
            "command": "python runtime",
            "returncode": 0,
            "output": json.dumps(
                {
                    "os_cpu_count": os.cpu_count(),
                    "sched_affinity_count": len(os.sched_getaffinity(0)) if hasattr(os, "sched_getaffinity") else None,
                    "sched_affinity": sorted(os.sched_getaffinity(0)) if hasattr(os, "sched_getaffinity") else None,
                    "OMP_NUM_THREADS": os.environ.get("OMP_NUM_THREADS", ""),
                    "MKL_NUM_THREADS": os.environ.get("MKL_NUM_THREADS", ""),
                    "OPENBLAS_NUM_THREADS": os.environ.get("OPENBLAS_NUM_THREADS", ""),
                    "NUMEXPR_NUM_THREADS": os.environ.get("NUMEXPR_NUM_THREADS", ""),
                    "CUDA_VISIBLE_DEVICES": os.environ.get("CUDA_VISIBLE_DEVICES", ""),
                },
                sort_keys=True,
            ),
        }
    )
    for row in rows:
        row["stage"] = stage
        row["run_name"] = args.run_name
        row["training_seed"] = int(args.seed)
        row["timestamp"] = time.strftime("%Y-%m-%d %H:%M:%S")
    append_csv(STEP_B_DIR / "tables/phase_n3pf_ms_seed2b_resource_affinity.csv", rows)


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def validate_config(cfg: dict[str, Any], args: argparse.Namespace, out_dir: Path) -> None:
    if not N3PF_MS_FLAG.exists():
        raise Seed2ABTrainStop("config_mismatch", f"missing prerequisite flag: {rel(N3PF_MS_FLAG)}")
    if out_dir.resolve() in [
        (ROOT / "checkpoints/env_v2_gpsi_heada_ppo_n3pf_ms_block_projected_s1").resolve(),
        (ROOT / "checkpoints/env_v2_gpsi_heada_ppo_n3pf_ms_block_projected_s2").resolve(),
    ]:
        raise Seed2ABTrainStop("config_mismatch", f"refusing to write original N3PF-MS checkpoint dir: {rel(out_dir)}")
    if args.run_name == "seed2_rerunA" and "s2_rerunA" not in out_dir.name:
        raise Seed2ABTrainStop("config_mismatch", f"seed2_rerunA out-dir must be isolated and include s2_rerunA: {rel(out_dir)}")
    if args.run_name == "seed3_sanity" and "s3_sanity" not in out_dir.name:
        raise Seed2ABTrainStop("config_mismatch", f"seed3_sanity out-dir must be isolated and include s3_sanity: {rel(out_dir)}")
    if int(args.train_steps) != 1_500_000:
        raise Seed2ABTrainStop("config_mismatch", f"Step B train_steps must be 1500000, got {args.train_steps}")
    if set(int(step) for step in args.checkpoint_steps) != set(CHECKPOINT_STEPS):
        raise Seed2ABTrainStop("config_mismatch", f"checkpoint steps must be {CHECKPOINT_STEPS}")
    if int(args.n_envs) != 4 or str(args.device) != "cpu":
        raise Seed2ABTrainStop("config_mismatch", f"Step B requires n_envs=4 and device=cpu, got n_envs={args.n_envs} device={args.device}")
    if args.run_name == "seed2_rerunA" and int(args.seed) != 2:
        raise Seed2ABTrainStop("config_mismatch", f"seed2_rerunA must use seed=2, got {args.seed}")
    if args.run_name == "seed3_sanity" and int(args.seed) != 3:
        raise Seed2ABTrainStop("config_mismatch", f"seed3_sanity must use seed=3, got {args.seed}")

    cfg["method_key"] = "block_projected"
    cfg["method_name"] = f"n3pf_ms_ab_block_projected_{args.run_name}"
    cfg.setdefault("env", {})["n_envs"] = int(args.n_envs)
    cfg.setdefault("env", {})["device"] = str(args.device)
    cfg.setdefault("training", {})["seed"] = int(args.seed)
    cfg["training"]["total_steps"] = int(args.train_steps)
    cfg["training"]["checkpoint_steps"] = [int(step) for step in args.checkpoint_steps]
    for key in ["parent_total_steps", "additional_steps", "resume", "reset_num_timesteps"]:
        cfg["training"].pop(key, None)
    cfg["training"]["no_shield"] = True
    cfg["training"]["action_filtering"] = False
    cfg["training"]["use_safety_cost"] = False
    n3p_train.validate_config_semantics(cfg)
    checkpoint = ROOT / str(cfg.get("gpsi", {}).get("checkpoint", "work_dirs/gpsi_heada_v1_nll/best.pth"))
    if not checkpoint.exists():
        raise Seed2ABTrainStop("gpsi_checkpoint_missing", f"missing Gpsi checkpoint: {rel(checkpoint)}")


def validate_wrapper(cfg: dict[str, Any], args: argparse.Namespace) -> None:
    env = n3p_train.make_wrapper(cfg, "eval_flow_id", args.device)
    try:
        obs, _info = env.reset(seed=int(args.seed))
        freeze = env.freeze_check
        expected = int(cfg.get("gpsi", {}).get("obs_aug_dim", 30))
        actual = int(obs["obs"].shape[-1])
        rows = [
            {"run_name": args.run_name, "training_seed": int(args.seed), "check": "gpsi_frozen", "value": int(not freeze.training and not freeze.requires_grad_any and freeze.trainable_parameters == 0), "detail": json.dumps(freeze.__dict__, sort_keys=True)},
            {"run_name": args.run_name, "training_seed": int(args.seed), "check": "aug_obs_dim", "value": actual, "detail": f"expected={expected}"},
            {"run_name": args.run_name, "training_seed": int(args.seed), "check": "include_z", "value": int(bool(env.latest_gpsi_debug.get("include_z", False))), "detail": "must be 0"},
            {"run_name": args.run_name, "training_seed": int(args.seed), "check": "feature_adapter", "value": str(cfg.get("ppo", {}).get("feature_adapter", "")), "detail": "must be block_projected_no_z"},
        ]
        append_csv(STEP_B_DIR / "tables/phase_n3pf_ms_seed2b_schema_check.csv", rows)
        if freeze.training or freeze.requires_grad_any or freeze.trainable_parameters != 0:
            raise Seed2ABTrainStop("config_mismatch", f"Gpsi freeze check failed: {freeze}")
        if actual != expected:
            raise Seed2ABTrainStop("config_mismatch", f"aug obs dim mismatch: {actual} vs {expected}")
        if bool(env.latest_gpsi_debug.get("include_z", False)):
            raise Seed2ABTrainStop("config_mismatch", "include_z must be false")
    finally:
        env.close()


def write_config_manifest(cfg: dict[str, Any], args: argparse.Namespace, out_dir: Path, adapter_count: int) -> None:
    gpsi = cfg.get("gpsi", {})
    ppo = cfg.get("ppo", {})
    append_csv(
        STEP_B_DIR / "tables/phase_n3pf_ms_seed2b_rerun_config_manifest.csv",
        [
            {
                "run_name": args.run_name,
                "training_seed": int(args.seed),
                "method_key": "block_projected",
                "method": cfg.get("method_name", ""),
                "config": rel(ROOT / args.config),
                "out_dir": rel(out_dir),
                "obs_aug_dim": int(gpsi.get("obs_aug_dim", -1)),
                "include_z": int(bool(gpsi.get("include_z", False))),
                "include_logvar": int(bool(gpsi.get("include_logvar", True))),
                "logvar_output_scale": float(gpsi.get("logvar_output_scale", 1.0)),
                "feature_adapter": str(ppo.get("feature_adapter", "")),
                "adapter_parameter_count": int(adapter_count),
                "train_steps": int(args.train_steps),
                "checkpoint_steps": json.dumps([int(step) for step in args.checkpoint_steps]),
                "n_envs": int(args.n_envs),
                "device": args.device,
                "no_shield": 1,
                "action_filtering": 0,
                "use_safety_cost": 0,
            }
        ],
    )


def write_command_manifest(args: argparse.Namespace, cfg: dict[str, Any], out_dir: Path) -> None:
    checkpoint = ROOT / str(cfg.get("gpsi", {}).get("checkpoint", "work_dirs/gpsi_heada_v1_nll/best.pth"))
    append_csv(
        STEP_B_DIR / "tables/phase_n3pf_ms_seed2b_command_manifest.csv",
        [
            {
                "stage": "train",
                "run_name": args.run_name,
                "training_seed": int(args.seed),
                "command": " ".join(["python", *sys.argv]),
                "config": rel(ROOT / args.config),
                "gpsi_checkpoint": rel(checkpoint),
                "gpsi_checkpoint_sha256": sha256(checkpoint) if checkpoint.exists() else "missing",
                "out_dir": rel(out_dir),
                "train_steps": int(args.train_steps),
                "checkpoint_steps": json.dumps([int(step) for step in args.checkpoint_steps]),
                "n_envs": int(args.n_envs),
                "device": args.device,
            }
        ],
    )


def policy_vector(model: PPO) -> torch.Tensor:
    return torch.cat([p.detach().cpu().float().reshape(-1) for p in model.policy.parameters()])


def write_checkpoint_integrity(args: argparse.Namespace, out_dir: Path) -> None:
    rows: list[dict[str, Any]] = []
    previous: torch.Tensor | None = None
    for label, filename, expected in [
        ("250k", "checkpoint_250k.zip", 250_000),
        ("500k", "checkpoint_500k.zip", 500_000),
        ("750k", "checkpoint_750k.zip", 750_000),
        ("1000k", "checkpoint_1000k.zip", 1_000_000),
        ("1250k", "checkpoint_1250k.zip", 1_250_000),
        ("1500k", "checkpoint_1500k.zip", 1_500_000),
        ("final", "final.zip", 1_500_000),
    ]:
        path = out_dir / filename
        exists = path.exists() and path.stat().st_size > 0
        row: dict[str, Any] = {
            "run_name": args.run_name,
            "training_seed": int(args.seed),
            "checkpoint_label": label,
            "checkpoint_path": rel(path),
            "exists": int(exists),
            "size_bytes": int(path.stat().st_size) if exists else 0,
            "sha256": sha256(path) if exists else "missing",
            "expected_total_steps": expected,
            "model_num_timesteps": np.nan,
            "optimizer_state_present": 0,
            "policy_parameter_l2_norm": np.nan,
            "policy_parameter_delta_vs_previous_checkpoint": np.nan,
        }
        if exists:
            model = PPO.load(str(path), device="cpu")
            params = policy_vector(model)
            row["model_num_timesteps"] = int(model.num_timesteps)
            row["optimizer_state_present"] = int(bool(model.policy.optimizer.state_dict().get("state", {})))
            row["policy_parameter_l2_norm"] = float(torch.linalg.vector_norm(params).item())
            if previous is not None and previous.numel() == params.numel():
                row["policy_parameter_delta_vs_previous_checkpoint"] = float(torch.linalg.vector_norm(params - previous).item())
            previous = params
            del model
        rows.append(row)
    write_csv(STEP_B_DIR / "tables/phase_n3pf_ms_seed2b_checkpoint_integrity.csv", rows)


def train() -> None:
    args = parse_args()
    out_dir = ROOT / args.out_dir
    ensure_dirs(out_dir)
    try:
        cfg = load_config(ROOT / args.config)
        validate_config(cfg, args, out_dir)
        if args.validate_only:
            write_resource_affinity("validate_only", args)
            validate_wrapper(cfg, args)
            print(
                f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] N3PF_MS_AB_VALIDATE_OK "
                f"run={args.run_name} seed={args.seed} out_dir={rel(out_dir)}",
                flush=True,
            )
            return
        action = base_train.prepare_training_guard(out_dir, cfg, args)
        if action in {"skip", "wait"}:
            write_checkpoint_integrity(args, out_dir)
            return
        save_yaml(out_dir / "config_resolved.yaml", cfg)
        write_resource_affinity("train_preflight", args)
        write_command_manifest(args, cfg, out_dir)
        set_seed(int(args.seed))
        validate_wrapper(cfg, args)

        env_fns = [n3p_train.make_env_factory(cfg, args, rank) for rank in range(int(args.n_envs))]
        vec_env = DummyVecEnv(env_fns)
        ppo_cfg = cfg.get("ppo", {})
        method_key = f"p3_s{int(args.seed)}_{args.run_name}"
        method_name = str(cfg.get("method_name", method_key))
        print(
            f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] N3PF_MS_AB_TRAIN_CONFIG "
            f"run={args.run_name} seed={args.seed} steps={args.train_steps} n_envs={args.n_envs} device={args.device} "
            f"out_dir={rel(out_dir)} no_shield=true",
            flush=True,
        )
        model = PPO(
            "MultiInputPolicy",
            vec_env,
            seed=int(args.seed),
            device=args.device,
            verbose=1,
            tensorboard_log=str(out_dir / "tensorboard"),
            policy_kwargs=n3p_train.make_policy_kwargs(cfg),
            n_steps=int(ppo_cfg.get("n_steps", 1024)),
            batch_size=int(ppo_cfg.get("batch_size", 256)),
            n_epochs=int(ppo_cfg.get("n_epochs", 10)),
            learning_rate=float(ppo_cfg.get("learning_rate", 3e-4)),
            gamma=float(ppo_cfg.get("gamma", 0.99)),
            gae_lambda=float(ppo_cfg.get("gae_lambda", 0.95)),
            clip_range=float(ppo_cfg.get("clip_range", 0.2)),
            ent_coef=float(ppo_cfg.get("ent_coef", 0.01)),
            vf_coef=float(ppo_cfg.get("vf_coef", 0.5)),
            max_grad_norm=float(ppo_cfg.get("max_grad_norm", 0.5)),
        )
        write_config_manifest(cfg, args, out_dir, n3p_train.adapter_parameter_count(model))
        callback = base_train.N3FZTrainCallback(int(args.train_steps), method_key, method_name, float(args.heartbeat_seconds))
        checkpoint_cb = base_train.FixedNameCheckpointCallback([int(step) for step in args.checkpoint_steps], out_dir)
        model.learn(total_timesteps=int(args.train_steps), callback=[callback, checkpoint_cb], progress_bar=False, reset_num_timesteps=True)
        final_path = out_dir / "final.zip"
        model.save(str(final_path))
        final_step_checkpoint = out_dir / f"checkpoint_{int(args.train_steps) // 1000}k.zip"
        if not final_step_checkpoint.exists():
            shutil.copyfile(final_path, final_step_checkpoint)
        episode_rows = [dict(row, run_name=args.run_name, training_seed=int(args.seed)) for row in callback.episode_rows]
        heartbeat_rows = [dict(row, run_name=args.run_name, training_seed=int(args.seed)) for row in callback.heartbeat_rows]
        append_csv(STEP_B_DIR / "tables/phase_n3pf_ms_seed2b_train_curve.csv", episode_rows)
        append_csv(STEP_B_DIR / "tables/phase_n3pf_ms_seed2b_train_heartbeat.csv", heartbeat_rows)
        write_checkpoint_integrity(args, out_dir)
        vec_env.close()
        base_train.complete_path(out_dir).write_text(f"completed\ntrain_steps={int(args.train_steps)}\ntraining_seed={int(args.seed)}\nrun_name={args.run_name}\n", encoding="utf-8")
        base_train.write_train_status(out_dir, "completed", cfg, args, "training completed successfully")
        base_train.lock_path(out_dir).unlink(missing_ok=True)
        print(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] N3PF_MS_AB_TRAIN_END run={args.run_name} seed={args.seed} final={rel(final_path)}", flush=True)
    except Seed2ABTrainStop as exc:
        write_stop(exc.reason, exc.detail)
        raise SystemExit(2) from exc
    except base_train.PhaseN3FZTrainStop as exc:
        write_stop("train_failed", exc.detail)
        raise SystemExit(2) from exc
    except Exception:
        detail = traceback.format_exc()
        try:
            if "cfg" in locals():
                base_train.write_train_status(out_dir, "failed", cfg, args, detail)
            base_train.lock_path(out_dir).unlink(missing_ok=True)
        except Exception:
            pass
        write_stop("train_failed", detail)
        raise SystemExit(2)


if __name__ == "__main__":
    train()
