from __future__ import annotations

import argparse
import csv
import json
import os
import random
import shutil
import socket
import subprocess
import sys
import time
import traceback
from pathlib import Path
from typing import Any

import numpy as np
import torch
import yaml
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import scripts.train_env_v2_gpsi_ppo_n3fz as base_train
import scripts.train_env_v2_gpsi_ppo_n3p as n3p_train


RESULT_DIR = ROOT / "results/env_v2_phase_n3pf_stab"
STOP_FLAGS = {
    "hard_error": "PHASE_N3PF_STAB_STOP_HARD_ERROR.flag",
    "training_broken": "PHASE_N3PF_STAB_STOP_TRAINING_BROKEN.flag",
    "resource_saturation": "PHASE_N3PF_STAB_STOP_RESOURCE_SATURATION.flag",
}


class StabTrainStop(Exception):
    def __init__(self, reason: str, detail: str) -> None:
        super().__init__(detail)
        self.reason = reason
        self.detail = detail


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train one Phase N3PF-STAB screening config.")
    parser.add_argument("--config", required=True)
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--train-steps", type=int, default=1_000_000)
    parser.add_argument("--checkpoint-steps", nargs="*", type=int, default=[500_000, 750_000, 1_000_000])
    parser.add_argument("--seed", type=int, default=2)
    parser.add_argument("--n-envs", type=int, default=4)
    parser.add_argument("--device", default="cpu")
    parser.add_argument("--heartbeat-seconds", type=float, default=300.0)
    parser.add_argument("--validate-only", action="store_true")
    return parser.parse_args()


def rel(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fields: list[str] = []
    seen: set[str] = set()
    for row in rows:
        for key in row:
            if key not in seen:
                seen.add(key)
                fields.append(key)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def append_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    old: list[dict[str, Any]] = []
    if path.exists() and path.stat().st_size > 0:
        with path.open("r", newline="", encoding="utf-8") as handle:
            old = list(csv.DictReader(handle))
    write_csv(path, old + rows)


def write_stop(reason: str, detail: str) -> None:
    RESULT_DIR.mkdir(parents=True, exist_ok=True)
    flag = STOP_FLAGS.get(reason, STOP_FLAGS["training_broken"])
    write_text(RESULT_DIR / flag, f"{reason}\n{detail.strip()}\n")
    write_text(RESULT_DIR / "phase_n3pf_stab_status.txt", f"stopped:{flag}\n")
    write_text(
        RESULT_DIR / "PHASE_N3PF_STAB_REPORT.md",
        "\n".join(
            [
                "# Phase N3PF-STAB Report",
                "",
                f"`terminal_decision = phase_n3pf_stab_stop_{reason}`",
                "",
                "Partial report generated by training script.",
                "",
                "```text",
                detail.strip(),
                "```",
            ]
        )
        + "\n",
    )


def load_config(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        payload = yaml.safe_load(handle)
    if not isinstance(payload, dict):
        raise StabTrainStop("hard_error", f"config is not a mapping: {rel(path)}")
    return payload


def save_yaml(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")


def run_command(label: str, command: list[str]) -> dict[str, Any]:
    try:
        proc = subprocess.run(command, check=False, text=True, capture_output=True, timeout=30)
        return {"item": label, "command": " ".join(command), "returncode": int(proc.returncode), "output": (proc.stdout + proc.stderr).strip()}
    except Exception as exc:
        return {"item": label, "command": " ".join(command), "returncode": -1, "output": f"{type(exc).__name__}: {exc}"}


def write_resource_affinity(stage: str, variant: str, seed: int) -> None:
    rows = [
        run_command("nproc", ["nproc"]),
        run_command("nproc_all", ["nproc", "--all"]),
        run_command("taskset_current_process", ["taskset", "-pc", str(os.getpid())]),
        run_command("free_h", ["free", "-h"]),
        run_command("df_root", ["df", "-h", "/"]),
    ]
    rows.append(
        {
            "item": "python_cpu_affinity",
            "command": "python runtime",
            "returncode": 0,
            "output": json.dumps(
                {
                    "hostname": socket.gethostname(),
                    "os_cpu_count": os.cpu_count(),
                    "sched_affinity_count": len(os.sched_getaffinity(0)) if hasattr(os, "sched_getaffinity") else None,
                    "sched_affinity": sorted(os.sched_getaffinity(0)) if hasattr(os, "sched_getaffinity") else None,
                    "OMP_NUM_THREADS": os.environ.get("OMP_NUM_THREADS", ""),
                    "MKL_NUM_THREADS": os.environ.get("MKL_NUM_THREADS", ""),
                    "OPENBLAS_NUM_THREADS": os.environ.get("OPENBLAS_NUM_THREADS", ""),
                    "NUMEXPR_NUM_THREADS": os.environ.get("NUMEXPR_NUM_THREADS", ""),
                    "CUDA_VISIBLE_DEVICES": os.environ.get("CUDA_VISIBLE_DEVICES", ""),
                },
                sort_keys=True,
            ),
        }
    )
    for row in rows:
        row["stage"] = stage
        row["variant"] = variant
        row["training_seed"] = int(seed)
        row["timestamp"] = time.strftime("%Y-%m-%d %H:%M:%S")
    append_csv(RESULT_DIR / "tables/phase_n3pf_stab_resource_affinity.csv", rows)


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def normalize_config(cfg: dict[str, Any], args: argparse.Namespace, out_dir: Path) -> None:
    variant = str(cfg.get("method_key", ""))
    if variant not in {"stab_s1_lr2e4", "stab_s1_lr1e4", "stab_s2d_gated"}:
        raise StabTrainStop("hard_error", f"unsupported STAB method_key={variant}")
    cfg.setdefault("env", {})["n_envs"] = int(args.n_envs)
    cfg["env"]["device"] = str(args.device)
    cfg.setdefault("training", {})["seed"] = int(args.seed)
    cfg["training"]["total_steps"] = int(args.train_steps)
    cfg["training"]["checkpoint_steps"] = [int(step) for step in args.checkpoint_steps]
    cfg["training"]["no_shield"] = True
    cfg["training"]["action_filtering"] = False
    cfg["training"]["use_safety_cost"] = False
    cfg["training"].pop("resume", None)
    cfg["training"].pop("reset_num_timesteps", None)
    cfg["training"]["out_dir"] = rel(out_dir)
    if int(args.n_envs) != 4 or str(args.device) != "cpu":
        raise StabTrainStop("hard_error", f"STAB requires n_envs=4 device=cpu, got n_envs={args.n_envs} device={args.device}")
    if int(args.train_steps) not in {1_000_000, 1_500_000}:
        raise StabTrainStop("hard_error", f"STAB train_steps must be 1000000 or 1500000, got {args.train_steps}")
    required = {500_000, 750_000, 1_000_000}
    if int(args.train_steps) == 1_500_000:
        required |= {1_250_000, 1_500_000}
    if not required.issubset({int(step) for step in args.checkpoint_steps}):
        raise StabTrainStop("hard_error", f"checkpoint_steps must include {sorted(required)}")
    gpsi = cfg.get("gpsi", {})
    if bool(gpsi.get("include_z", False)) or int(gpsi.get("obs_aug_dim", 30)) != 30:
        raise StabTrainStop("hard_error", "STAB configs must be no_z obs_aug_dim=30")
    adapter = str(cfg.get("ppo", {}).get("feature_adapter"))
    if adapter == "gated_residual_no_z":
        if str(cfg.get("s2_variant", "")) != "S2-D":
            raise StabTrainStop("hard_error", "gated config must explicitly declare S2-D")
    else:
        cfg["method_key"] = "block_projected"
        n3p_train.validate_config_semantics(cfg)
    if adapter == "gated_residual_no_z":
        if bool(gpsi.get("include_z", False)) or not bool(gpsi.get("include_logvar", True)):
            raise StabTrainStop("hard_error", "S2-D must be no_z with logvar included")
        if int(gpsi.get("obs_aug_dim", -1)) != 30:
            raise StabTrainStop("hard_error", "S2-D requires obs_aug_dim=30")
        if abs(float(gpsi.get("logvar_output_scale", 1.0)) - 0.2) > 1e-9:
            raise StabTrainStop("hard_error", "S2-D requires logvar_output_scale=0.2")
        training = cfg.get("training", {})
        if not bool(training.get("no_shield", True)) or bool(training.get("action_filtering", False)) or bool(training.get("use_safety_cost", False)):
            raise StabTrainStop("hard_error", "S2-D requires no shield/action filtering/safety cost")
    cfg["method_key"] = variant
    checkpoint = ROOT / str(gpsi.get("checkpoint", "work_dirs/gpsi_heada_v1_nll/best.pth"))
    if not checkpoint.exists():
        raise StabTrainStop("hard_error", f"missing Gpsi checkpoint: {rel(checkpoint)}")


def validate_wrapper(cfg: dict[str, Any], args: argparse.Namespace) -> None:
    env = n3p_train.make_wrapper(cfg, "eval_flow_id", args.device)
    try:
        obs, _info = env.reset(seed=int(args.seed))
        freeze = env.freeze_check
        rows = [
            {"variant": cfg["method_key"], "training_seed": int(args.seed), "check": "gpsi_frozen", "value": int(not freeze.training and not freeze.requires_grad_any and freeze.trainable_parameters == 0), "detail": json.dumps(freeze.__dict__, sort_keys=True)},
            {"variant": cfg["method_key"], "training_seed": int(args.seed), "check": "aug_obs_dim", "value": int(obs["obs"].shape[-1]), "detail": "expected=30"},
            {"variant": cfg["method_key"], "training_seed": int(args.seed), "check": "include_z", "value": int(bool(env.latest_gpsi_debug.get("include_z", False))), "detail": "must be 0"},
            {"variant": cfg["method_key"], "training_seed": int(args.seed), "check": "feature_adapter", "value": str(cfg.get("ppo", {}).get("feature_adapter", "")), "detail": "block_projected_no_z or gated_residual_no_z"},
        ]
        append_csv(RESULT_DIR / "tables/phase_n3pf_stab_schema_check.csv", rows)
        if freeze.training or freeze.requires_grad_any or freeze.trainable_parameters != 0:
            raise StabTrainStop("hard_error", f"Gpsi freeze check failed: {freeze}")
        if int(obs["obs"].shape[-1]) != 30:
            raise StabTrainStop("hard_error", f"obs dim mismatch: {obs['obs'].shape[-1]} vs 30")
    finally:
        env.close()


def write_manifests(args: argparse.Namespace, cfg: dict[str, Any], out_dir: Path, model: PPO | None = None) -> None:
    checkpoint = ROOT / str(cfg.get("gpsi", {}).get("checkpoint", "work_dirs/gpsi_heada_v1_nll/best.pth"))
    ppo = cfg.get("ppo", {})
    rows = [
        {
            "stage": "train",
            "variant": cfg["method_key"],
            "method_name": cfg.get("method_name", cfg["method_key"]),
            "training_seed": int(args.seed),
            "command": " ".join(["python", *sys.argv]),
            "config": rel(ROOT / args.config),
            "out_dir": rel(out_dir),
            "gpsi_checkpoint": rel(checkpoint),
            "gpsi_checkpoint_sha256": base_train.sha256(checkpoint) if checkpoint.exists() else "missing",
            "learning_rate": float(ppo.get("learning_rate", np.nan)),
            "feature_adapter": str(ppo.get("feature_adapter", "")),
            "s2_variant": str(cfg.get("s2_variant", "")),
            "s2_claim": str(cfg.get("s2_claim", "")),
            "train_steps": int(args.train_steps),
            "checkpoint_steps": json.dumps([int(step) for step in args.checkpoint_steps]),
            "n_envs": int(args.n_envs),
            "device": args.device,
            "adapter_parameter_count": int(n3p_train.adapter_parameter_count(model)) if model is not None else -1,
        }
    ]
    append_csv(RESULT_DIR / "tables/phase_n3pf_stab_command_manifest.csv", rows)
    append_csv(RESULT_DIR / "tables/phase_n3pf_stab_config_manifest.csv", rows)


def train() -> None:
    args = parse_args()
    out_dir = ROOT / args.out_dir
    for path in [out_dir, RESULT_DIR / "logs", RESULT_DIR / "tables", RESULT_DIR / "plots"]:
        path.mkdir(parents=True, exist_ok=True)
    try:
        cfg = load_config(ROOT / args.config)
        normalize_config(cfg, args, out_dir)
        if args.validate_only:
            write_resource_affinity("validate_only", cfg["method_key"], int(args.seed))
            validate_wrapper(cfg, args)
            write_manifests(args, cfg, out_dir, None)
            print(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] STAB_VALIDATE_OK variant={cfg['method_key']} seed={args.seed}", flush=True)
            return
        action = base_train.prepare_training_guard(out_dir, cfg, args)
        if action in {"skip", "wait"}:
            return
        save_yaml(out_dir / "config_resolved.yaml", cfg)
        write_resource_affinity("train_preflight", cfg["method_key"], int(args.seed))
        validate_wrapper(cfg, args)
        set_seed(int(args.seed))

        env_fns = [n3p_train.make_env_factory(cfg, args, rank) for rank in range(int(args.n_envs))]
        vec_env = DummyVecEnv(env_fns)
        ppo_cfg = cfg.get("ppo", {})
        model = PPO(
            "MultiInputPolicy",
            vec_env,
            seed=int(args.seed),
            device=args.device,
            verbose=1,
            tensorboard_log=str(out_dir / "tensorboard"),
            policy_kwargs=n3p_train.make_policy_kwargs(cfg),
            n_steps=int(ppo_cfg.get("n_steps", 1024)),
            batch_size=int(ppo_cfg.get("batch_size", 256)),
            n_epochs=int(ppo_cfg.get("n_epochs", 10)),
            learning_rate=float(ppo_cfg.get("learning_rate", 3e-4)),
            gamma=float(ppo_cfg.get("gamma", 0.99)),
            gae_lambda=float(ppo_cfg.get("gae_lambda", 0.95)),
            clip_range=float(ppo_cfg.get("clip_range", 0.2)),
            ent_coef=float(ppo_cfg.get("ent_coef", 0.01)),
            vf_coef=float(ppo_cfg.get("vf_coef", 0.5)),
            max_grad_norm=float(ppo_cfg.get("max_grad_norm", 0.5)),
        )
        write_manifests(args, cfg, out_dir, model)
        callback = base_train.N3FZTrainCallback(int(args.train_steps), cfg["method_key"], str(cfg.get("method_name", cfg["method_key"])), float(args.heartbeat_seconds))
        checkpoint_cb = base_train.FixedNameCheckpointCallback([int(step) for step in args.checkpoint_steps], out_dir)
        model.learn(total_timesteps=int(args.train_steps), callback=[callback, checkpoint_cb], progress_bar=False, reset_num_timesteps=True)
        final_path = out_dir / "final.zip"
        model.save(str(final_path))
        final_step_checkpoint = out_dir / f"checkpoint_{int(args.train_steps) // 1000}k.zip"
        if not final_step_checkpoint.exists():
            shutil.copyfile(final_path, final_step_checkpoint)
        train_rows = [dict(row, variant=cfg["method_key"], training_seed=int(args.seed), learning_rate=float(ppo_cfg.get("learning_rate", np.nan))) for row in callback.episode_rows]
        heartbeat_rows = [dict(row, variant=cfg["method_key"], training_seed=int(args.seed), learning_rate=float(ppo_cfg.get("learning_rate", np.nan))) for row in callback.heartbeat_rows]
        append_csv(RESULT_DIR / "tables/phase_n3pf_stab_train_curve.csv", train_rows)
        append_csv(RESULT_DIR / "tables/phase_n3pf_stab_train_heartbeat.csv", heartbeat_rows)
        vec_env.close()
        base_train.complete_path(out_dir).write_text(f"completed\ntrain_steps={int(args.train_steps)}\ntraining_seed={int(args.seed)}\nvariant={cfg['method_key']}\n", encoding="utf-8")
        base_train.write_train_status(out_dir, "completed", cfg, args, "training completed successfully")
        base_train.lock_path(out_dir).unlink(missing_ok=True)
        print(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] STAB_TRAIN_END variant={cfg['method_key']} seed={args.seed} final={rel(final_path)}", flush=True)
    except StabTrainStop as exc:
        write_stop(exc.reason, exc.detail)
        raise SystemExit(2) from exc
    except Exception:
        detail = traceback.format_exc()
        try:
            if "cfg" in locals():
                base_train.write_train_status(out_dir, "failed", cfg, args, detail)
            base_train.lock_path(out_dir).unlink(missing_ok=True)
        except Exception:
            pass
        write_stop("training_broken", detail)
        raise SystemExit(2)


if __name__ == "__main__":
    train()
