#!/usr/bin/env bash
set -u -o pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

OUT_DIR="results/env_v2_phase_n4o_ordinary_shield_fair_comparison"
LOG_DIR="$OUT_DIR/logs"
mkdir -p "$LOG_DIR" "$OUT_DIR/tables" "$OUT_DIR/plots"

COMPLETE_FLAG="$OUT_DIR/PHASE_N4O_ORDINARY_SHIELD_FAIR_COMPARISON_COMPLETE.flag"
STATUS_FILE="$OUT_DIR/phase_n4o_status.txt"
WATCHER_LOG="$OUT_DIR/phase_n4o_watcher.log"

STOP_FLAGS=(
  PHASE_N4O_STOP_CHECKPOINT_MISSING.flag
  PHASE_N4O_STOP_PHASE_B_CONFIG_MISSING.flag
  PHASE_N4O_STOP_SHIELD_CONFIG_MISMATCH.flag
  PHASE_N4O_STOP_SIGMA_USED_BY_ORDINARY_SHIELD.flag
  PHASE_N4O_STOP_EVAL_FAILED.flag
  PHASE_N4O_STOP_SCHEMA_INVALID.flag
  PHASE_N4O_STOP_WATCHER_FAILED.flag
)

log() {
  local msg="[$(date '+%Y-%m-%d %H:%M:%S')] $*"
  echo "$msg" | tee -a "$WATCHER_LOG"
}

stop_phase() {
  local flag="$1"
  local detail="$2"
  echo "$detail" > "$OUT_DIR/$flag"
  echo "stopped:$flag" > "$STATUS_FILE"
  cat > "$OUT_DIR/PHASE_N4O_ORDINARY_SHIELD_FAIR_COMPARISON_REPORT.md" <<EOF
# Phase N4-O Ordinary Shield Fair Comparison Report

\`terminal_decision = phase_n4o_stopped_${flag%.flag}\`

Partial report generated by watcher.

\`\`\`text
$detail
\`\`\`
EOF
  log "STOP $flag $detail"
  exit 2
}

run_stage() {
  local name="$1"
  shift
  log "START $name: $*"
  "$@"
  local rc=$?
  log "END $name rc=$rc"
  return "$rc"
}

rm -rf "$OUT_DIR/tables" "$OUT_DIR/plots" "$LOG_DIR"
mkdir -p "$LOG_DIR" "$OUT_DIR/tables" "$OUT_DIR/plots"
rm -f "$COMPLETE_FLAG"
for flag in "${STOP_FLAGS[@]}"; do
  rm -f "$OUT_DIR/$flag"
done
echo "running" > "$STATUS_FILE"
: > "$WATCHER_LOG"

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export CUDA_VISIBLE_DEVICES=""

run_stage py_compile python -m py_compile \
  scripts/eval_env_v2_phase_n4o_ordinary_shield.py \
  scripts/analyze_env_v2_phase_n4o_results.py || stop_phase "PHASE_N4O_STOP_WATCHER_FAILED.flag" "py_compile failed"

run_stage eval nice -n 10 python -u scripts/eval_env_v2_phase_n4o_ordinary_shield.py \
  --result-dir "$OUT_DIR" \
  --eval-seeds 1000 1001 1002 \
  --num-episodes 50 \
  --scenarios eval_flow_id eval_flow_high_density eval_flow_high_speed eval_flow_high_threat eval_flow_mixed_ood eval_flow_sudden_threat \
  --shield-config-name vo_like_filter_h45_cpa1p2_h16 \
  --device cpu \
  --heartbeat-seconds 300 \
  > "$LOG_DIR/phase_n4o_eval.log" 2>&1 || stop_phase "PHASE_N4O_STOP_EVAL_FAILED.flag" "N4-O eval failed"

run_stage analysis python -u scripts/analyze_env_v2_phase_n4o_results.py \
  --result-dir "$OUT_DIR" \
  --expected-seeds 1000 1001 1002 \
  --expected-episodes 50 \
  > "$LOG_DIR/phase_n4o_analysis.log" 2>&1 || stop_phase "PHASE_N4O_STOP_SCHEMA_INVALID.flag" "N4-O analysis failed"

if [[ -f "$COMPLETE_FLAG" ]]; then
  echo "complete" > "$STATUS_FILE"
  log "complete flag detected"
  exit 0
fi

stop_phase "PHASE_N4O_STOP_WATCHER_FAILED.flag" "analysis exited without complete flag"
