#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export CUDA_VISIBLE_DEVICES=""

RESULT_DIR="results/env_v2_phase_n3pf_stab"
LOG_DIR="${RESULT_DIR}/logs"
WATCHER_LOG="${RESULT_DIR}/phase_n3pf_stab_watcher.log"
STATUS_FILE="${RESULT_DIR}/phase_n3pf_stab_status.txt"
COMPLETE_FLAG="${RESULT_DIR}/PHASE_N3PF_STAB_COMPLETE.flag"
SYNC_COMMIT_FILE="${RESULT_DIR}/github_sync_commit.txt"

STOP_FLAGS=(
  "PHASE_N3PF_STAB_STOP_HARD_ERROR.flag"
  "PHASE_N3PF_STAB_STOP_VALIDATION_TEST_LEAKAGE.flag"
  "PHASE_N3PF_STAB_STOP_TRAINING_BROKEN.flag"
  "PHASE_N3PF_STAB_STOP_RESOURCE_SATURATION.flag"
  "PHASE_N3PF_STAB_STOP_EVAL_FAILED.flag"
)

SCENARIOS=(
  eval_flow_id
  eval_flow_high_density
  eval_flow_high_speed
  eval_flow_high_threat
  eval_flow_mixed_ood
  eval_flow_sudden_threat
)

RUN_LR2="stab_s1_lr2e4:2:configs/env_v2_gpsi_heada_ppo_n3pf_stab_s1_lr2e4.yaml:checkpoints/env_v2_gpsi_heada_ppo_n3pf_stab/stab_s1_lr2e4_s2"
RUN_LR1="stab_s1_lr1e4:2:configs/env_v2_gpsi_heada_ppo_n3pf_stab_s1_lr1e4.yaml:checkpoints/env_v2_gpsi_heada_ppo_n3pf_stab/stab_s1_lr1e4_s2"
RUN_S2D="stab_s2d_gated:2:configs/env_v2_gpsi_heada_ppo_n3pf_stab_s2d_gated.yaml:checkpoints/env_v2_gpsi_heada_ppo_n3pf_stab/stab_s2d_gated_s2"

mkdir -p "$RESULT_DIR" "$LOG_DIR" "${RESULT_DIR}/tables" "${RESULT_DIR}/plots"

log() {
  local msg="$*"
  printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$msg" | tee -a "$WATCHER_LOG"
}

set_status() {
  printf '%s\n' "$*" > "$STATUS_FILE"
}

has_stop_flag() {
  local flag
  for flag in "${STOP_FLAGS[@]}"; do
    if [[ -f "${RESULT_DIR}/${flag}" ]]; then
      echo "$flag"
      return 0
    fi
  done
  return 1
}

write_watcher_stop() {
  local reason="$1"
  local detail="$2"
  local flag="${RESULT_DIR}/PHASE_N3PF_STAB_STOP_HARD_ERROR.flag"
  case "$reason" in
    training_broken)
      flag="${RESULT_DIR}/PHASE_N3PF_STAB_STOP_TRAINING_BROKEN.flag"
      ;;
    validation_test_leakage)
      flag="${RESULT_DIR}/PHASE_N3PF_STAB_STOP_VALIDATION_TEST_LEAKAGE.flag"
      ;;
    resource_saturation)
      flag="${RESULT_DIR}/PHASE_N3PF_STAB_STOP_RESOURCE_SATURATION.flag"
      ;;
  esac
  printf '%s\n%s\n' "$reason" "$detail" > "$flag"
  set_status "stopped:$(basename "$flag")"
  cat > "${RESULT_DIR}/PHASE_N3PF_STAB_REPORT.md" <<EOF_REPORT
# Phase N3PF-STAB Report

\`terminal_decision = phase_n3pf_stab_stop_${reason}\`

Partial report generated by watcher.

\`\`\`text
${detail}
\`\`\`
EOF_REPORT
}

run_stage() {
  local label="$1"
  local log_file="$2"
  shift 2
  log "START ${label}: $*"
  set_status "running:${label}"
  set +e
  "$@" > "$log_file" 2>&1
  local rc=$?
  set -e
  if [[ "$rc" -ne 0 ]]; then
    log "FAIL ${label} rc=${rc}; tail follows"
    tail -n 120 "$log_file" | tee -a "$WATCHER_LOG"
    local stop_flag
    if stop_flag="$(has_stop_flag)"; then
      log "STOP flag detected after ${label}: ${stop_flag}"
      set_status "stopped:${stop_flag}"
      exit 0
    fi
    write_watcher_stop "hard_error" "${label} failed rc=${rc}; see ${log_file}"
    exit 0
  fi
  log "END ${label}"
  tail -n 30 "$log_file" | tee -a "$WATCHER_LOG" >/dev/null || true
  local stop_flag
  if stop_flag="$(has_stop_flag)"; then
    log "STOP flag detected after ${label}: ${stop_flag}"
    set_status "stopped:${stop_flag}"
    exit 0
  fi
}

run_bg_stage() {
  local label="$1"
  local log_file="$2"
  shift 2
  log "START ${label}: $*"
  set_status "running:${label}"
  "$@" > "$log_file" 2>&1 &
  BG_PID="$!"
}

wait_bg_pair() {
  local pid_a="$1"
  local label_a="$2"
  local log_a="$3"
  local pid_b="$4"
  local label_b="$5"
  local log_b="$6"
  local last_heartbeat=0
  while kill -0 "$pid_a" 2>/dev/null || kill -0 "$pid_b" 2>/dev/null; do
    local now
    now="$(date +%s)"
    if (( now - last_heartbeat >= 300 )); then
      log "HEARTBEAT training ${label_a} pid_alive=$(kill -0 "$pid_a" 2>/dev/null && echo yes || echo no), ${label_b} pid_alive=$(kill -0 "$pid_b" 2>/dev/null && echo yes || echo no)"
      tail -n 6 "$log_a" | tee -a "$WATCHER_LOG" >/dev/null || true
      tail -n 6 "$log_b" | tee -a "$WATCHER_LOG" >/dev/null || true
      last_heartbeat="$now"
    fi
    sleep 120
  done
  local rc_a=0
  local rc_b=0
  wait "$pid_a" || rc_a=$?
  wait "$pid_b" || rc_b=$?
  if [[ "$rc_a" -ne 0 ]]; then
    log "FAIL ${label_a} rc=${rc_a}; tail follows"
    tail -n 120 "$log_a" | tee -a "$WATCHER_LOG"
    write_watcher_stop "training_broken" "${label_a} failed rc=${rc_a}; see ${log_a}"
    exit 0
  fi
  if [[ "$rc_b" -ne 0 ]]; then
    log "FAIL ${label_b} rc=${rc_b}; tail follows"
    tail -n 120 "$log_b" | tee -a "$WATCHER_LOG"
    write_watcher_stop "training_broken" "${label_b} failed rc=${rc_b}; see ${log_b}"
    exit 0
  fi
  log "END ${label_a} and ${label_b}"
}

if [[ -f "$COMPLETE_FLAG" ]]; then
  log "complete flag already exists; exiting"
  set_status "complete"
  exit 0
fi

log "Phase N3PF-STAB watcher start pid=$$"
set_status "running:preflight"

git rev-parse HEAD > "$SYNC_COMMIT_FILE" || true
SYNC_COMMIT="$(cat "$SYNC_COMMIT_FILE" 2>/dev/null || echo unknown)"

run_stage "py_compile" "${LOG_DIR}/phase_n3pf_stab_py_compile.log" \
  python -m py_compile \
    models/gpsi_ppo_policy.py \
    scripts/train_env_v2_gpsi_ppo_n3p.py \
    scripts/eval_env_v2_gpsi_ppo_n3p.py \
    scripts/train_env_v2_gpsi_ppo_n3pf_stab.py \
    scripts/eval_env_v2_gpsi_ppo_n3pf_stab.py \
    scripts/select_env_v2_phase_n3pf_stab_checkpoint.py \
    scripts/analyze_env_v2_phase_n3pf_stab.py

run_stage "bash_n" "${LOG_DIR}/phase_n3pf_stab_bash_n.log" \
  bash -n scripts/watch_phase_n3pf_stab.sh

run_stage "validate_lr2e4" "${LOG_DIR}/phase_n3pf_stab_validate_lr2e4.log" \
  python scripts/train_env_v2_gpsi_ppo_n3pf_stab.py \
    --config configs/env_v2_gpsi_heada_ppo_n3pf_stab_s1_lr2e4.yaml \
    --out-dir checkpoints/env_v2_gpsi_heada_ppo_n3pf_stab/stab_s1_lr2e4_s2 \
    --train-steps 1000000 \
    --checkpoint-steps 500000 750000 1000000 \
    --seed 2 --n-envs 4 --device cpu --heartbeat-seconds 300 --validate-only

run_stage "validate_lr1e4" "${LOG_DIR}/phase_n3pf_stab_validate_lr1e4.log" \
  python scripts/train_env_v2_gpsi_ppo_n3pf_stab.py \
    --config configs/env_v2_gpsi_heada_ppo_n3pf_stab_s1_lr1e4.yaml \
    --out-dir checkpoints/env_v2_gpsi_heada_ppo_n3pf_stab/stab_s1_lr1e4_s2 \
    --train-steps 1000000 \
    --checkpoint-steps 500000 750000 1000000 \
    --seed 2 --n-envs 4 --device cpu --heartbeat-seconds 300 --validate-only

run_stage "validate_s2d" "${LOG_DIR}/phase_n3pf_stab_validate_s2d.log" \
  python scripts/train_env_v2_gpsi_ppo_n3pf_stab.py \
    --config configs/env_v2_gpsi_heada_ppo_n3pf_stab_s2d_gated.yaml \
    --out-dir checkpoints/env_v2_gpsi_heada_ppo_n3pf_stab/stab_s2d_gated_s2 \
    --train-steps 1000000 \
    --checkpoint-steps 500000 750000 1000000 \
    --seed 2 --n-envs 4 --device cpu --heartbeat-seconds 300 --validate-only

log "Launching S1 lower-LR screening jobs in parallel, max concurrency=2."
run_bg_stage "train_lr2e4" "${LOG_DIR}/phase_n3pf_stab_train_lr2e4.log" \
  python scripts/train_env_v2_gpsi_ppo_n3pf_stab.py \
    --config configs/env_v2_gpsi_heada_ppo_n3pf_stab_s1_lr2e4.yaml \
    --out-dir checkpoints/env_v2_gpsi_heada_ppo_n3pf_stab/stab_s1_lr2e4_s2 \
    --train-steps 1000000 \
    --checkpoint-steps 500000 750000 1000000 \
    --seed 2 --n-envs 4 --device cpu --heartbeat-seconds 300
pid_lr2="$BG_PID"
run_bg_stage "train_lr1e4" "${LOG_DIR}/phase_n3pf_stab_train_lr1e4.log" \
  python scripts/train_env_v2_gpsi_ppo_n3pf_stab.py \
    --config configs/env_v2_gpsi_heada_ppo_n3pf_stab_s1_lr1e4.yaml \
    --out-dir checkpoints/env_v2_gpsi_heada_ppo_n3pf_stab/stab_s1_lr1e4_s2 \
    --train-steps 1000000 \
    --checkpoint-steps 500000 750000 1000000 \
    --seed 2 --n-envs 4 --device cpu --heartbeat-seconds 300
pid_lr1="$BG_PID"
wait_bg_pair "$pid_lr2" "train_lr2e4" "${LOG_DIR}/phase_n3pf_stab_train_lr2e4.log" "$pid_lr1" "train_lr1e4" "${LOG_DIR}/phase_n3pf_stab_train_lr1e4.log"

run_stage "train_s2d" "${LOG_DIR}/phase_n3pf_stab_train_s2d.log" \
  python scripts/train_env_v2_gpsi_ppo_n3pf_stab.py \
    --config configs/env_v2_gpsi_heada_ppo_n3pf_stab_s2d_gated.yaml \
    --out-dir checkpoints/env_v2_gpsi_heada_ppo_n3pf_stab/stab_s2d_gated_s2 \
    --train-steps 1000000 \
    --checkpoint-steps 500000 750000 1000000 \
    --seed 2 --n-envs 4 --device cpu --heartbeat-seconds 300

run_stage "validation_eval" "${LOG_DIR}/phase_n3pf_stab_validation_eval.log" \
  python scripts/eval_env_v2_gpsi_ppo_n3pf_stab.py \
    --result-dir "$RESULT_DIR" \
    --eval-phase validation \
    --run "$RUN_LR2" \
    --run "$RUN_LR1" \
    --run "$RUN_S2D" \
    --checkpoint-labels 500k 750k 1000k final \
    --eval-seeds 900 901 \
    --num-episodes 50 \
    --scenarios "${SCENARIOS[@]}" \
    --device cpu \
    --heartbeat-seconds 300

run_stage "selector" "${LOG_DIR}/phase_n3pf_stab_selector.log" \
  python scripts/select_env_v2_phase_n3pf_stab_checkpoint.py \
    --result-dir "$RESULT_DIR" \
    --selection-metric success_minus_2collision \
    --validation-seeds 900 901

run_stage "analysis_report" "${LOG_DIR}/phase_n3pf_stab_analysis.log" \
  python scripts/analyze_env_v2_phase_n3pf_stab.py \
    --result-dir "$RESULT_DIR" \
    --mode post_validation \
    --github-sync-status pushed \
    --github-sync-commit "$SYNC_COMMIT"

if [[ -f "$COMPLETE_FLAG" ]]; then
  log "COMPLETE ${COMPLETE_FLAG}"
  set_status "complete"
  exit 0
fi

write_watcher_stop "hard_error" "analysis finished but complete flag is missing"
log "STOP complete flag missing after analysis"
exit 0
