#!/usr/bin/env bash
set -u
set -o pipefail

RESULT_DIR="results/env_v2_phase_n3fz_noz_full_z_screen"
LOG_DIR="${RESULT_DIR}/logs"
TABLE_DIR="${RESULT_DIR}/tables"
WATCHER_LOG="${RESULT_DIR}/phase_n3fz_watcher.log"
STATUS_FILE="${RESULT_DIR}/phase_n3fz_status.txt"
COMPLETE_FLAG="${RESULT_DIR}/PHASE_N3FZ_NOZ_FULL_Z_SCREEN_COMPLETE.flag"

NOZ_STEPS="${N3FZ_NOZ_STEPS:-1500000}"
Z_STEPS="${N3FZ_Z_STEPS:-500000}"
EVAL_EPISODES="${N3FZ_EVAL_EPISODES:-50}"
N_ENVS="${N3FZ_N_ENVS:-4}"
DEVICE="${N3FZ_DEVICE:-cuda}"
HEARTBEAT="${N3FZ_HEARTBEAT_SECONDS:-30}"

mkdir -p "${LOG_DIR}" "${TABLE_DIR}" "${RESULT_DIR}/plots" "${RESULT_DIR}/traces"
: > "${WATCHER_LOG}"

log() {
  local message="$1"
  printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "${message}" | tee -a "${WATCHER_LOG}"
}

stop() {
  local reason="$1"
  local detail="$2"
  local flag="${RESULT_DIR}/PHASE_N3FZ_STOP_${reason}.flag"
  printf '%s\n%s\n' "${reason}" "${detail}" > "${flag}"
  printf 'stopped:%s\n' "$(basename "${flag}")" > "${STATUS_FILE}"
  if [[ ! -s "${RESULT_DIR}/PHASE_N3FZ_NOZ_FULL_Z_SCREEN_REPORT.md" ]]; then
    {
      printf '# Phase N3F/Z No-Z Full + Z Screen Report\n\n'
      printf '`terminal_decision = phase_n3fz_stopped_%s`\n\n' "$(echo "${reason}" | tr '[:upper:]' '[:lower:]')"
      printf 'Partial report generated by watcher.\n\n'
      printf '```text\n%s\n```\n\n' "${detail}"
      printf 'Can enter N4: no.\n'
    } > "${RESULT_DIR}/PHASE_N3FZ_NOZ_FULL_Z_SCREEN_REPORT.md"
  fi
  log "STOP ${reason}: ${detail}"
  exit 2
}

run_stage() {
  local stage="$1"
  local log_file="$2"
  shift 2
  log "START ${stage}: $*"
  "$@" > "${log_file}" 2>&1
  local code=$?
  if [[ ${code} -ne 0 ]]; then
    log "FAILED ${stage} exit_code=${code}; tail follows"
    tail -n 100 "${log_file}" | tee -a "${WATCHER_LOG}" || true
    case "${stage}" in
      z_stats) stop "Z_STATS_FAILED" "${stage} failed; see ${log_file}" ;;
      train_no_z_full|train_z_l2_scale_4|train_z_layernorm_alpha_0p5) stop "TRAIN_FAILED" "${stage} failed; see ${log_file}" ;;
      eval) stop "EVAL_FAILED" "${stage} failed; see ${log_file}" ;;
      analysis) stop "ANALYSIS_FAILED" "${stage} failed; see ${log_file}" ;;
      *) stop "WATCHER_FAILED" "${stage} failed; see ${log_file}" ;;
    esac
  fi
  log "END ${stage}"
}

log "Phase N3F/Z watcher started"
printf 'running\n' > "${STATUS_FILE}"
rm -f "${RESULT_DIR}"/*.flag
rm -f "${TABLE_DIR}"/phase_n3fz_*.csv

[[ -f results/env_v2_phase_n3r_gpsi_ppo_rerun/PHASE_N3R_GPSI_PPO_RERUN_COMPLETE.flag ]] || stop "PHASE_N3R_MISSING" "missing Phase N3R complete flag"
[[ -f results/env_v2_phase_n3_5_gpsi_wrapper_audit/PHASE_N3_5_GPSI_WRAPPER_AUDIT_COMPLETE.flag ]] || stop "PHASE_N3_5_MISSING" "missing Phase N3.5 complete flag"
[[ -f work_dirs/gpsi_heada_v1_nll/best.pth ]] || stop "GPSI_CHECKPOINT_MISSING" "missing Gpsi checkpoint work_dirs/gpsi_heada_v1_nll/best.pth"

log "syntax checks"
python -m py_compile scripts/compute_gpsi_z_stats.py || stop "WATCHER_FAILED" "py_compile compute_gpsi_z_stats.py failed"
python -m py_compile scripts/train_env_v2_gpsi_ppo_n3fz.py || stop "WATCHER_FAILED" "py_compile train_env_v2_gpsi_ppo_n3fz.py failed"
python -m py_compile scripts/eval_env_v2_gpsi_ppo_n3fz.py || stop "WATCHER_FAILED" "py_compile eval_env_v2_gpsi_ppo_n3fz.py failed"
python -m py_compile scripts/analyze_env_v2_phase_n3fz_results.py || stop "WATCHER_FAILED" "py_compile analyze_env_v2_phase_n3fz_results.py failed"
bash -n scripts/watch_phase_n3fz_noz_full_z_screen.sh || stop "WATCHER_FAILED" "bash -n watcher failed"

run_stage z_stats "${LOG_DIR}/phase_n3fz_z_stats.log" \
  python scripts/compute_gpsi_z_stats.py \
    --data-dir data/gpsi_head_a_v1 \
    --checkpoint work_dirs/gpsi_heada_v1_nll/best.pth \
    --out "${TABLE_DIR}/phase_n3fz_z_stats.csv" \
    --out-npz work_dirs/gpsi_heada_v1_nll/z_stats_train_split_n3fz_reference.npz \
    --split train \
    --max-samples 200000 \
    --device "${DEVICE}"

run_stage train_no_z_full "${LOG_DIR}/phase_n3fz_train_no_z_full.log" \
  python scripts/train_env_v2_gpsi_ppo_n3fz.py \
    --config configs/env_v2_gpsi_heada_ppo_n3f_no_z_full.yaml \
    --out-dir checkpoints/env_v2_gpsi_heada_ppo_n3f_no_z_s0 \
    --train-steps "${NOZ_STEPS}" \
    --checkpoint-steps 250000 500000 1000000 "${NOZ_STEPS}" \
    --seed 0 \
    --n-envs "${N_ENVS}" \
    --device "${DEVICE}" \
    --heartbeat-seconds "${HEARTBEAT}"

run_stage train_z_l2_scale_4 "${LOG_DIR}/phase_n3fz_train_z_l2_scale_4.log" \
  python scripts/train_env_v2_gpsi_ppo_n3fz.py \
    --config configs/env_v2_gpsi_heada_ppo_n3z_l2_scale4.yaml \
    --out-dir checkpoints/env_v2_gpsi_heada_ppo_n3z_l2_scale4_s0 \
    --train-steps "${Z_STEPS}" \
    --checkpoint-steps 250000 "${Z_STEPS}" \
    --seed 0 \
    --n-envs "${N_ENVS}" \
    --device "${DEVICE}" \
    --heartbeat-seconds "${HEARTBEAT}"

run_stage train_z_layernorm_alpha_0p5 "${LOG_DIR}/phase_n3fz_train_z_layernorm_alpha_0p5.log" \
  python scripts/train_env_v2_gpsi_ppo_n3fz.py \
    --config configs/env_v2_gpsi_heada_ppo_n3z_layernorm_alpha0p5.yaml \
    --out-dir checkpoints/env_v2_gpsi_heada_ppo_n3z_layernorm_alpha0p5_s0 \
    --train-steps "${Z_STEPS}" \
    --checkpoint-steps 250000 "${Z_STEPS}" \
    --seed 0 \
    --n-envs "${N_ENVS}" \
    --device "${DEVICE}" \
    --heartbeat-seconds "${HEARTBEAT}"

run_stage eval "${LOG_DIR}/phase_n3fz_eval.log" \
  python scripts/eval_env_v2_gpsi_ppo_n3fz.py \
    --result-dir "${RESULT_DIR}" \
    --configs n3f_no_z_full z_l2_scale_4 z_layernorm_alpha_0p5 \
    --eval-seed 1000 \
    --num-episodes "${EVAL_EPISODES}" \
    --device "${DEVICE}" \
    --scenarios eval_flow_id eval_flow_high_density eval_flow_high_speed eval_flow_high_threat eval_flow_mixed_ood eval_flow_sudden_threat \
    --write-traces

run_stage analysis "${LOG_DIR}/phase_n3fz_analysis.log" \
  python scripts/analyze_env_v2_phase_n3fz_results.py \
    --result-dir "${RESULT_DIR}" \
    --expected-episodes "${EVAL_EPISODES}" \
    --expected-noz-steps "${NOZ_STEPS}" \
    --expected-z-steps "${Z_STEPS}"

if [[ -f "${COMPLETE_FLAG}" ]]; then
  log "COMPLETE flag present: ${COMPLETE_FLAG}"
  printf 'complete\n' > "${STATUS_FILE}"
  exit 0
fi

stop "WATCHER_FAILED" "analysis exited without complete flag"
