#!/usr/bin/env bash
set -euo pipefail

RESULT_DIR="results/env_v2_phase_n3z2c_z2_continuation"
TABLE_DIR="${RESULT_DIR}/tables"
LOG_DIR="${RESULT_DIR}/logs"
PLOT_DIR="${RESULT_DIR}/plots"
WATCHER_LOG="${RESULT_DIR}/phase_n3z2c_watcher.log"
STATUS_FILE="${RESULT_DIR}/phase_n3z2c_status.txt"
OUT_DIR="checkpoints/env_v2_gpsi_heada_ppo_n3z2c_layernorm_alpha0p5_s0"
CONFIG="configs/env_v2_gpsi_heada_ppo_n3z2c_layernorm_alpha0p5_1p5m.yaml"
SCENARIOS=(eval_flow_id eval_flow_high_density eval_flow_high_speed eval_flow_high_threat eval_flow_mixed_ood eval_flow_sudden_threat)

mkdir -p "${TABLE_DIR}" "${LOG_DIR}" "${PLOT_DIR}" "${OUT_DIR}"
rm -f "${RESULT_DIR}"/*.flag
rm -f "${TABLE_DIR}"/phase_n3z2c_*.csv "${TABLE_DIR}"/phase_n3z2c_*.json
rm -f "${PLOT_DIR}"/*.png
: > "${WATCHER_LOG}"
printf 'running\n' > "${STATUS_FILE}"

log() {
  local msg="$1"
  printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "${msg}" | tee -a "${WATCHER_LOG}"
}

stop() {
  local reason="$1"
  local detail="$2"
  local flag="${RESULT_DIR}/PHASE_N3Z2C_STOP_${reason}.flag"
  printf '%s\n%s\n' "${reason}" "${detail}" > "${flag}"
  printf 'stopped:%s\n' "$(basename "${flag}")" > "${STATUS_FILE}"
  {
    printf '# Phase N3Z2C Z2 Continuation Report\n\n'
    printf '`terminal_decision = phase_n3z2c_stopped_%s`\n\n' "$(echo "${reason}" | tr '[:upper:]' '[:lower:]')"
    printf 'Partial report generated by watcher.\n\n```text\n%s\n```\n\nCan enter N4: no.\n' "${detail}"
  } > "${RESULT_DIR}/PHASE_N3Z2C_Z2_CONTINUATION_REPORT.md"
  log "STOP ${reason}: ${detail}"
  exit 2
}

run_stage() {
  local stage="$1"
  local log_file="$2"
  shift 2
  log "START ${stage}: $*"
  printf 'stage:%s\n' "${stage}" > "${STATUS_FILE}"
  if ! "$@" > "${log_file}" 2>&1; then
    case "${stage}" in
      resource_preflight) stop "WATCHER_FAILED" "resource preflight failed; see ${log_file}" ;;
      parent_selection) stop "Z2_PARENT_MISSING" "parent selection failed; see ${log_file}" ;;
      benchmark_*) stop "RESOURCE_BENCHMARK_FAILED" "${stage} failed; see ${log_file}" ;;
      train_z2_continuation) stop "TRAIN_FAILED" "Z2 continuation failed; see ${log_file}" ;;
      eval) stop "EVAL_FAILED" "eval failed; see ${log_file}" ;;
      analysis) stop "DIAGNOSTICS_FAILED" "analysis failed; see ${log_file}" ;;
      *) stop "WATCHER_FAILED" "${stage} failed; see ${log_file}" ;;
    esac
  fi
  log "END ${stage}"
}

if [[ ! -f "results/env_v2_phase_n3fz_noz_full_z_screen/PHASE_N3FZ_NOZ_FULL_Z_SCREEN_COMPLETE.flag" ]]; then
  stop "PHASE_N3FZ_MISSING" "Phase N3F/Z complete flag is missing"
fi
if [[ ! -f "work_dirs/gpsi_heada_v1_nll/best.pth" ]]; then
  stop "Z2_PARENT_MISSING" "Gpsi checkpoint missing"
fi

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1

python -m py_compile scripts/train_env_v2_gpsi_ppo_n3z2c.py || stop "WATCHER_FAILED" "py_compile train failed"
python -m py_compile scripts/eval_env_v2_gpsi_ppo_n3z2c.py || stop "WATCHER_FAILED" "py_compile eval failed"
python -m py_compile scripts/analyze_env_v2_phase_n3z2c_results.py || stop "WATCHER_FAILED" "py_compile analysis failed"
python -m py_compile scripts/select_phase_n3z2c_parent.py || stop "WATCHER_FAILED" "py_compile parent selection failed"
python -m py_compile scripts/phase_n3z2c_resource_preflight.py || stop "WATCHER_FAILED" "py_compile resource preflight failed"
python -m py_compile scripts/phase_n3z2c_benchmark_summary.py || stop "WATCHER_FAILED" "py_compile benchmark summary failed"
bash -n scripts/watch_phase_n3z2c_z2_continuation.sh || stop "WATCHER_FAILED" "bash -n watcher failed"

run_stage resource_preflight "${LOG_DIR}/phase_n3z2c_resource_preflight.log" \
  python scripts/phase_n3z2c_resource_preflight.py \
    --out "${TABLE_DIR}/phase_n3z2c_resource_preflight.csv" \
    --log "${LOG_DIR}/phase_n3z2c_resource_preflight_detail.log"

run_stage parent_selection "${LOG_DIR}/phase_n3z2c_parent_selection.log" \
  python scripts/select_phase_n3z2c_parent.py \
    --out "${TABLE_DIR}/phase_n3z2c_parent_checkpoint_selection.csv"

PARENT="$(python - <<'PY'
import json
from pathlib import Path
p=Path('results/env_v2_phase_n3z2c_z2_continuation/tables/phase_n3z2c_parent_checkpoint_selection.json')
print(json.loads(p.read_text())['selected_parent_path'])
PY
)"
cp -f "${PARENT}" "${OUT_DIR}/parent_500k.zip"
log "SELECTED_PARENT ${PARENT}"

for nenv in 4; do
  bench_dir="checkpoints/env_v2_gpsi_heada_ppo_n3z2c_benchmark_nenv${nenv}"
  rm -rf "${bench_dir}"
  run_stage "benchmark_nenv${nenv}" "${LOG_DIR}/phase_n3z2c_benchmark_nenv${nenv}.log" \
    python scripts/train_env_v2_gpsi_ppo_n3z2c.py \
      --config "${CONFIG}" \
      --resume "${PARENT}" \
      --out-dir "${bench_dir}" \
      --additional-steps 2048 \
      --parent-total-steps 500000 \
      --target-total-steps 502048 \
      --checkpoint-total-steps 502048 \
      --seed 0 \
      --n-envs "${nenv}" \
      --device cpu \
      --benchmark-only \
      --heartbeat-seconds 5
done

python scripts/phase_n3z2c_benchmark_summary.py \
  --logs \
    "${LOG_DIR}/phase_n3z2c_benchmark_nenv4.log" \
  --out "${TABLE_DIR}/phase_n3z2c_cpu_benchmark.csv" \
  --selected-n-envs 4 \
  --skipped-n-envs 8 12 \
  --selection-reason "Kept n_envs=4 because increasing n_envs changes PPO rollout batch semantics versus N3F/Z; benchmark is audit-only." \
  >> "${WATCHER_LOG}" 2>&1

rm -f "${OUT_DIR}/TRAIN_RUNNING.lock" "${OUT_DIR}/TRAIN_COMPLETE.flag" "${OUT_DIR}/TRAIN_STATUS.json"
rm -f "${OUT_DIR}/checkpoint_750k.zip" "${OUT_DIR}/checkpoint_1000k.zip" "${OUT_DIR}/checkpoint_1250k.zip" "${OUT_DIR}/checkpoint_1500k.zip" "${OUT_DIR}/final.zip" "${OUT_DIR}/best_by_eval.zip"

run_stage train_z2_continuation "${LOG_DIR}/phase_n3z2c_train_z2_continuation.log" \
  python scripts/train_env_v2_gpsi_ppo_n3z2c.py \
    --config "${CONFIG}" \
    --resume "${PARENT}" \
    --out-dir "${OUT_DIR}" \
    --additional-steps 1000000 \
    --parent-total-steps 500000 \
    --target-total-steps 1500000 \
    --checkpoint-total-steps 750000 1000000 1250000 1500000 \
    --seed 0 \
    --n-envs 4 \
    --device cpu \
    --heartbeat-seconds 30

run_stage eval "${LOG_DIR}/phase_n3z2c_eval.log" \
  python scripts/eval_env_v2_gpsi_ppo_n3z2c.py \
    --result-dir "${RESULT_DIR}" \
    --z2-checkpoint-dir "${OUT_DIR}" \
    --noz-reference-dir checkpoints/env_v2_gpsi_heada_ppo_n3f_no_z_s0 \
    --attention-checkpoint checkpoints/env_v2_phase2/attention_full_s0/attention_full_s0_step1500000.zip \
    --eval-seed 1000 \
    --num-episodes 50 \
    --device cpu \
    --scenarios "${SCENARIOS[@]}" \
    --write-traces

run_stage analysis "${LOG_DIR}/phase_n3z2c_analysis.log" \
  python scripts/analyze_env_v2_phase_n3z2c_results.py \
    --result-dir "${RESULT_DIR}" \
    --noz-success 0.5633 \
    --noz-collision 0.4367 \
    --attention-success 0.6100 \
    --attention-collision 0.3900

if [[ -f "${RESULT_DIR}/PHASE_N3Z2C_Z2_CONTINUATION_COMPLETE.flag" ]]; then
  printf 'complete\n' > "${STATUS_FILE}"
  log "COMPLETE flag present: ${RESULT_DIR}/PHASE_N3Z2C_Z2_CONTINUATION_COMPLETE.flag"
  exit 0
fi

stop "WATCHER_FAILED" "pipeline ended without complete flag"
