#!/usr/bin/env bash
set -euo pipefail

OUT_DIR="results/env_v2_phase_n3_gpsi_ppo_no_shield"
LOG="$OUT_DIR/phase_n3_watcher.log"
STATUS="$OUT_DIR/phase_n3_status.txt"
CONFIG="configs/env_v2_gpsi_heada_attention_ppo_v1.yaml"
GPSI_CKPT="work_dirs/gpsi_heada_v1_nll/best.pth"
SMOKE_DIR="checkpoints/env_v2_gpsi_heada_ppo_s0_smoke"
FORMAL_DIR="checkpoints/env_v2_gpsi_heada_ppo_s0"
ATTENTION_CKPT="checkpoints/env_v2_phase2/attention_full_s0/attention_full_s0_step1500000.zip"

mkdir -p "$OUT_DIR/logs" "$OUT_DIR/tables" "$OUT_DIR/plots" "$OUT_DIR/traces"
: > "$LOG"
echo "[watcher] Phase N3 watcher started $(date -Is)" | tee -a "$LOG"
echo "running" > "$STATUS"

stop_flags=(
  PHASE_N3_STOP_PHASE_N2_MISSING.flag
  PHASE_N3_STOP_GPSI_CHECKPOINT_MISSING.flag
  PHASE_N3_STOP_GPSI_WRAPPER_FAILED.flag
  PHASE_N3_STOP_GPSI_NOT_FROZEN.flag
  PHASE_N3_STOP_SCHEMA_MISMATCH.flag
  PHASE_N3_STOP_TRAIN_FAILED.flag
  PHASE_N3_STOP_EVAL_FAILED.flag
  PHASE_N3_STOP_RESOURCE_LIMIT.flag
  PHASE_N3_STOP_TRACE_DIAGNOSTICS_FAILED.flag
  PHASE_N3_STOP_WATCHER_FAILED.flag
)

terminal_check() {
  if [[ -f "$OUT_DIR/PHASE_N3_GPSI_PPO_NO_SHIELD_COMPLETE.flag" ]]; then
    echo "complete" > "$STATUS"
    echo "[watcher] complete flag detected" | tee -a "$LOG"
    exit 0
  fi
  for flag in "${stop_flags[@]}"; do
    if [[ -f "$OUT_DIR/$flag" ]]; then
      echo "stopped:$flag" > "$STATUS"
      echo "[watcher] stop flag detected: $flag" | tee -a "$LOG"
      exit 2
    fi
  done
}

write_stop() {
  local flag="$1"
  local reason="$2"
  echo "$reason" > "$OUT_DIR/$flag"
  echo "stopped:$flag" > "$STATUS"
  {
    echo "# Phase N3 Gpsi-PPO No-Shield Report"
    echo
    echo "\`terminal_decision = phase_n3_stopped_${reason}\`"
    echo
    echo "Partial report generated by watcher."
  } > "$OUT_DIR/PHASE_N3_GPSI_PPO_NO_SHIELD_REPORT.md"
  terminal_check
}

run_stage() {
  local stage="$1"
  shift
  local stage_log="$OUT_DIR/logs/phase_n3_${stage}.log"
  echo "[watcher] running stage=$stage command=$*" | tee -a "$LOG"
  echo "running:$stage" > "$STATUS"
  if "$@" > "$stage_log" 2>&1; then
    echo "[watcher] stage complete: $stage" | tee -a "$LOG"
  else
    local rc=$?
    echo "[watcher] stage failed: $stage rc=$rc" | tee -a "$LOG"
    tail -n 80 "$stage_log" | tee -a "$LOG" || true
    terminal_check
    case "$stage" in
      smoke|formal_train)
        touch "$OUT_DIR/PHASE_N3_STOP_TRAIN_FAILED.flag"
        ;;
      eval)
        touch "$OUT_DIR/PHASE_N3_STOP_EVAL_FAILED.flag"
        ;;
      analysis)
        touch "$OUT_DIR/PHASE_N3_STOP_TRACE_DIAGNOSTICS_FAILED.flag"
        ;;
      *)
        touch "$OUT_DIR/PHASE_N3_STOP_WATCHER_FAILED.flag"
        ;;
    esac
    terminal_check
  fi
  terminal_check
}

if [[ ! -f "results/env_v2_phase_n2_gpsi_heada_offline/PHASE_N2_HEADA_OFFLINE_COMPLETE.flag" ]]; then
  write_stop "PHASE_N3_STOP_PHASE_N2_MISSING.flag" "phase_n2_missing"
fi

if [[ ! -f "$GPSI_CKPT" ]]; then
  write_stop "PHASE_N3_STOP_GPSI_CHECKPOINT_MISSING.flag" "gpsi_checkpoint_missing"
fi

if [[ ! -f "$ATTENTION_CKPT" ]]; then
  write_stop "PHASE_N3_STOP_EVAL_FAILED.flag" "attention_reference_missing"
fi

rm -f "$OUT_DIR/PHASE_N3_GPSI_PPO_NO_SHIELD_COMPLETE.flag"
for flag in "${stop_flags[@]}"; do
  rm -f "$OUT_DIR/$flag"
done

run_stage smoke \
  python scripts/train_env_v2_gpsi_ppo.py \
    --config "$CONFIG" \
    --gpsi-checkpoint "$GPSI_CKPT" \
    --out-dir "$SMOKE_DIR" \
    --train-steps 2048 \
    --checkpoint-steps 2048 \
    --seed 0 \
    --smoke-test \
    --heartbeat-seconds 5

run_stage formal_train \
  python scripts/train_env_v2_gpsi_ppo.py \
    --config "$CONFIG" \
    --gpsi-checkpoint "$GPSI_CKPT" \
    --out-dir "$FORMAL_DIR" \
    --train-steps 1500000 \
    --checkpoint-steps 250000 500000 1000000 1500000 \
    --seed 0 \
    --heartbeat-seconds 60

run_stage eval \
  python scripts/eval_env_v2_gpsi_ppo.py \
    --gpsi-checkpoint "$GPSI_CKPT" \
    --ppo-checkpoints \
      "$FORMAL_DIR/checkpoint_500k.zip" \
      "$FORMAL_DIR/checkpoint_1000k.zip" \
      "$FORMAL_DIR/checkpoint_1500k.zip" \
    --attention-checkpoint "$ATTENTION_CKPT" \
    --out-dir "$OUT_DIR" \
    --scenarios eval_flow_id eval_flow_high_density eval_flow_high_speed eval_flow_high_threat eval_flow_mixed_ood eval_flow_sudden_threat \
    --num-episodes 50 \
    --eval-seed 1000 \
    --write-traces \
    --raw-unsafe-diagnostics \
    --gpsi-output-diagnostics \
    --heartbeat-seconds 30

run_stage analysis \
  python scripts/analyze_env_v2_phase_n3_results.py \
    --result-dir "$OUT_DIR"

while true; do
  terminal_check
  echo "[watcher] waiting for terminal flag..." | tee -a "$LOG"
  sleep 60
done
