#!/usr/bin/env bash
set -u -o pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

OUT_DIR="results/env_v2_phase_n3pf_ms_multiseed"
LOG_DIR="$OUT_DIR/logs"
mkdir -p "$LOG_DIR" "$OUT_DIR/tables" "$OUT_DIR/plots"

COMPLETE_FLAG="$OUT_DIR/PHASE_N3PF_MS_MULTI_SEED_COMPLETE.flag"
STATUS_FILE="$OUT_DIR/phase_n3pf_ms_status.txt"
WATCHER_LOG="$OUT_DIR/phase_n3pf_ms_watcher.log"

STOP_FLAGS=(
  PHASE_N3PF_MS_STOP_CONFIG_MISMATCH.flag
  PHASE_N3PF_MS_STOP_GPSI_CHECKPOINT_MISSING.flag
  PHASE_N3PF_MS_STOP_TRAIN_FAILED.flag
  PHASE_N3PF_MS_STOP_EVAL_FAILED.flag
  PHASE_N3PF_MS_STOP_DIAGNOSTICS_FAILED.flag
  PHASE_N3PF_MS_STOP_PARALLEL_RESOURCE_UNSAFE.flag
  PHASE_N3PF_MS_STOP_WATCHER_FAILED.flag
)

log() {
  local msg="[$(date '+%Y-%m-%d %H:%M:%S')] $*"
  echo "$msg" | tee -a "$WATCHER_LOG"
}

stop_phase() {
  local flag="$1"
  local detail="$2"
  echo "$detail" > "$OUT_DIR/$flag"
  echo "stopped:$flag" > "$STATUS_FILE"
  cat > "$OUT_DIR/PHASE_N3PF_MS_MULTI_SEED_REPORT.md" <<EOF
# Phase N3PF-MS Multi-Training-Seed Report

\`terminal_decision = phase_n3pf_ms_stopped_${flag%.flag}\`

Partial report generated by watcher.

\`\`\`text
$detail
\`\`\`
EOF
  log "STOP $flag $detail"
  exit 2
}

has_stop() {
  for flag in "${STOP_FLAGS[@]}"; do
    if [[ -f "$OUT_DIR/$flag" ]]; then
      echo "$flag"
      return 0
    fi
  done
  return 1
}

run_stage() {
  local name="$1"
  shift
  log "START $name: $*"
  "$@"
  local rc=$?
  log "END $name rc=$rc"
  return "$rc"
}

rm -rf "$OUT_DIR/tables" "$OUT_DIR/plots" "$LOG_DIR"
mkdir -p "$LOG_DIR" "$OUT_DIR/tables" "$OUT_DIR/plots"
rm -f "$COMPLETE_FLAG"
for flag in "${STOP_FLAGS[@]}"; do
  rm -f "$OUT_DIR/$flag"
done
echo "running" > "$STATUS_FILE"
: > "$WATCHER_LOG"

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export CUDA_VISIBLE_DEVICES=""

run_stage py_compile python -m py_compile \
  scripts/train_env_v2_gpsi_ppo_n3pf_ms.py \
  scripts/eval_env_v2_gpsi_ppo_n3pf_ms.py \
  scripts/analyze_env_v2_phase_n3pf_ms_results.py || stop_phase "PHASE_N3PF_MS_STOP_WATCHER_FAILED.flag" "py_compile failed"

run_stage validate_seed1 python scripts/train_env_v2_gpsi_ppo_n3pf_ms.py \
  --config configs/env_v2_gpsi_heada_ppo_n3pf_block_projected.yaml \
  --out-dir checkpoints/env_v2_gpsi_heada_ppo_n3pf_ms_block_projected_s1 \
  --train-steps 1500000 \
  --checkpoint-steps 250000 500000 750000 1000000 1250000 1500000 \
  --seed 1 \
  --n-envs 4 \
  --device cpu \
  --validate-only >> "$LOG_DIR/phase_n3pf_ms_validate_s1.log" 2>&1 || stop_phase "PHASE_N3PF_MS_STOP_CONFIG_MISMATCH.flag" "seed1 validation failed"

run_stage validate_seed2 python scripts/train_env_v2_gpsi_ppo_n3pf_ms.py \
  --config configs/env_v2_gpsi_heada_ppo_n3pf_block_projected.yaml \
  --out-dir checkpoints/env_v2_gpsi_heada_ppo_n3pf_ms_block_projected_s2 \
  --train-steps 1500000 \
  --checkpoint-steps 250000 500000 750000 1000000 1250000 1500000 \
  --seed 2 \
  --n-envs 4 \
  --device cpu \
  --validate-only >> "$LOG_DIR/phase_n3pf_ms_validate_s2.log" 2>&1 || stop_phase "PHASE_N3PF_MS_STOP_CONFIG_MISMATCH.flag" "seed2 validation failed"

log "launching seed1/seed2 training in parallel"
env OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 CUDA_VISIBLE_DEVICES="" \
  python -u scripts/train_env_v2_gpsi_ppo_n3pf_ms.py \
  --config configs/env_v2_gpsi_heada_ppo_n3pf_block_projected.yaml \
  --out-dir checkpoints/env_v2_gpsi_heada_ppo_n3pf_ms_block_projected_s1 \
  --train-steps 1500000 \
  --checkpoint-steps 250000 500000 750000 1000000 1250000 1500000 \
  --seed 1 \
  --n-envs 4 \
  --device cpu \
  --heartbeat-seconds 300 \
  > "$LOG_DIR/phase_n3pf_ms_train_s1.log" 2>&1 &
PID1=$!

env OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 CUDA_VISIBLE_DEVICES="" \
  python -u scripts/train_env_v2_gpsi_ppo_n3pf_ms.py \
  --config configs/env_v2_gpsi_heada_ppo_n3pf_block_projected.yaml \
  --out-dir checkpoints/env_v2_gpsi_heada_ppo_n3pf_ms_block_projected_s2 \
  --train-steps 1500000 \
  --checkpoint-steps 250000 500000 750000 1000000 1250000 1500000 \
  --seed 2 \
  --n-envs 4 \
  --device cpu \
  --heartbeat-seconds 300 \
  > "$LOG_DIR/phase_n3pf_ms_train_s2.log" 2>&1 &
PID2=$!

log "train PIDs seed1=$PID1 seed2=$PID2"

wait "$PID1"
RC1=$?
wait "$PID2"
RC2=$?
log "training finished rc_seed1=$RC1 rc_seed2=$RC2"

if [[ "$RC1" -ne 0 || "$RC2" -ne 0 ]]; then
  stop_phase "PHASE_N3PF_MS_STOP_TRAIN_FAILED.flag" "seed training failed rc_seed1=$RC1 rc_seed2=$RC2"
fi

if [[ -n "$(has_stop || true)" ]]; then
  stop_phase "$(has_stop)" "stop flag appeared after training"
fi

run_stage eval python -u scripts/eval_env_v2_gpsi_ppo_n3pf_ms.py \
  --result-dir "$OUT_DIR" \
  --training-seeds 1 2 \
  --eval-seeds 1000 1001 1002 \
  --num-episodes 50 \
  --scenarios eval_flow_id eval_flow_high_density eval_flow_high_speed eval_flow_high_threat eval_flow_mixed_ood eval_flow_sudden_threat \
  --device cpu \
  --heartbeat-seconds 300 \
  > "$LOG_DIR/phase_n3pf_ms_eval.log" 2>&1 || stop_phase "PHASE_N3PF_MS_STOP_EVAL_FAILED.flag" "N3PF-MS eval failed"

run_stage analysis python -u scripts/analyze_env_v2_phase_n3pf_ms_results.py \
  --result-dir "$OUT_DIR" \
  --expected-training-seeds 1 2 \
  --expected-eval-seeds 1000 1001 1002 \
  --expected-episodes 50 \
  > "$LOG_DIR/phase_n3pf_ms_analysis.log" 2>&1 || stop_phase "PHASE_N3PF_MS_STOP_DIAGNOSTICS_FAILED.flag" "N3PF-MS analysis failed"

if [[ -f "$COMPLETE_FLAG" ]]; then
  echo "complete" > "$STATUS_FILE"
  log "complete flag detected"
  exit 0
fi

stop_phase "PHASE_N3PF_MS_STOP_WATCHER_FAILED.flag" "analysis exited without complete flag"
