#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export CUDA_VISIBLE_DEVICES=""

RESULT_DIR="results/env_v2_phase_n3pf_ms_seed2_ab_audit_rerun"
STEP_A_DIR="${RESULT_DIR}/step_a_audit"
STEP_B_DIR="${RESULT_DIR}/step_b_rerun"
LOG_DIR="${RESULT_DIR}/logs"
WATCHER_LOG="${RESULT_DIR}/phase_n3pf_ms_seed2_ab_watcher.log"
STATUS_FILE="${RESULT_DIR}/phase_n3pf_ms_seed2_ab_status.txt"
COMPLETE_FLAG="${RESULT_DIR}/PHASE_N3PF_MS_SEED2_AB_AUDIT_RERUN_COMPLETE.flag"

STOP_FLAGS=(
  "PHASE_N3PF_MS_AB_STOP_CONFIG_MISMATCH.flag"
  "PHASE_N3PF_MS_AB_STOP_EVAL_PATH_MISMATCH.flag"
  "PHASE_N3PF_MS_AB_STOP_CHECKPOINT_INTEGRITY_FAILED.flag"
  "PHASE_N3PF_MS_AB_STOP_FEATURE_GPSI_DIAGNOSTICS_FAILED.flag"
  "PHASE_N3PF_MS_AB_STOP_TRAIN_FAILED.flag"
  "PHASE_N3PF_MS_AB_STOP_EVAL_FAILED.flag"
  "PHASE_N3PF_MS_AB_STOP_RESOURCE_UNSAFE.flag"
  "PHASE_N3PF_MS_AB_STOP_WATCHER_FAILED.flag"
)

SCENARIOS=(
  eval_flow_id
  eval_flow_high_density
  eval_flow_high_speed
  eval_flow_high_threat
  eval_flow_mixed_ood
  eval_flow_sudden_threat
)

mkdir -p "$RESULT_DIR" "$STEP_A_DIR/tables" "$STEP_A_DIR/plots" "$STEP_A_DIR/logs" "$STEP_B_DIR/tables" "$STEP_B_DIR/plots" "$STEP_B_DIR/logs" "$LOG_DIR"

log() {
  local msg="$*"
  printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$msg" | tee -a "$WATCHER_LOG"
}

set_status() {
  printf '%s\n' "$*" > "$STATUS_FILE"
}

has_stop_flag() {
  local flag
  for flag in "${STOP_FLAGS[@]}"; do
    if [[ -f "${RESULT_DIR}/${flag}" ]]; then
      echo "$flag"
      return 0
    fi
  done
  return 1
}

write_watcher_stop() {
  local reason="$1"
  local detail="$2"
  local flag="${RESULT_DIR}/PHASE_N3PF_MS_AB_STOP_WATCHER_FAILED.flag"
  printf '%s\n%s\n' "$reason" "$detail" > "$flag"
  set_status "stopped:PHASE_N3PF_MS_AB_STOP_WATCHER_FAILED.flag"
  cat > "${RESULT_DIR}/PHASE_N3PF_MS_SEED2_AB_AUDIT_RERUN_REPORT.md" <<EOF_REPORT
# Phase N3PF-MS-AB Seed2 Collapse Audit + Minimal Rerun Sanity

\`terminal_decision = phase_n3pf_ms_seed2_ab_stopped_watcher_failed\`

Partial report generated by watcher.

\`\`\`text
${detail}
\`\`\`
EOF_REPORT
}

run_stage() {
  local label="$1"
  local log_file="$2"
  shift 2
  log "START ${label}: $*"
  set_status "running:${label}"
  set +e
  "$@" > "$log_file" 2>&1
  local rc=$?
  set -e
  if [[ "$rc" -ne 0 ]]; then
    log "FAIL ${label} rc=${rc}; tail follows"
    tail -n 80 "$log_file" | tee -a "$WATCHER_LOG"
    local stop_flag
    if stop_flag="$(has_stop_flag)"; then
      log "STOP flag detected after ${label}: ${stop_flag}"
      set_status "stopped:${stop_flag}"
      exit 0
    fi
    write_watcher_stop "watcher_failed" "${label} failed rc=${rc}; see ${log_file}"
    exit 0
  fi
  log "END ${label}"
  tail -n 20 "$log_file" | tee -a "$WATCHER_LOG" >/dev/null || true
  local stop_flag
  if stop_flag="$(has_stop_flag)"; then
    log "STOP flag detected after ${label}: ${stop_flag}"
    set_status "stopped:${stop_flag}"
    exit 0
  fi
}

if [[ -f "$COMPLETE_FLAG" ]]; then
  log "complete flag already exists; exiting"
  set_status "complete"
  exit 0
fi

log "Phase N3PF-MS-AB watcher start pid=$$"
set_status "running:preflight"

run_stage "py_compile" "${LOG_DIR}/phase_n3pf_ms_seed2_ab_py_compile.log" \
  python -m py_compile \
    scripts/audit_env_v2_phase_n3pf_ms_seed2.py \
    scripts/train_env_v2_gpsi_ppo_n3pf_ms_seed2_rerun.py \
    scripts/eval_env_v2_gpsi_ppo_n3pf_ms_seed2_ab.py \
    scripts/analyze_env_v2_phase_n3pf_ms_seed2_ab.py

run_stage "bash_n" "${LOG_DIR}/phase_n3pf_ms_seed2_ab_bash_n.log" \
  bash -n scripts/watch_phase_n3pf_ms_seed2_ab.sh

run_stage "step_a_audit" "${STEP_A_DIR}/logs/phase_n3pf_ms_seed2a_audit.log" \
  python scripts/audit_env_v2_phase_n3pf_ms_seed2.py \
    --source-result-dir results/env_v2_phase_n3pf_ms_multiseed \
    --result-dir "$RESULT_DIR" \
    --out-dir "$STEP_A_DIR" \
    --seed-good 1 \
    --seed-bad 2 \
    --include-seed0 \
    --write-plots

run_stage "step_a_intermediate_eval" "${STEP_A_DIR}/logs/phase_n3pf_ms_seed2a_intermediate_eval.log" \
  python scripts/eval_env_v2_gpsi_ppo_n3pf_ms_seed2_ab.py \
    --mode intermediate_eval \
    --result-dir "$RESULT_DIR" \
    --out-dir "$STEP_A_DIR" \
    --source-result-dir results/env_v2_phase_n3pf_ms_multiseed \
    --training-seeds 1 2 \
    --checkpoints checkpoint_250k checkpoint_500k checkpoint_750k checkpoint_1250k \
    --eval-seeds 1000 1001 \
    --num-episodes 50 \
    --scenarios "${SCENARIOS[@]}" \
    --device cpu \
    --heartbeat-seconds 300

run_stage "step_b_validate_seed2_rerunA" "${STEP_B_DIR}/logs/phase_n3pf_ms_seed2b_validate_seed2_rerunA.log" \
  python scripts/train_env_v2_gpsi_ppo_n3pf_ms_seed2_rerun.py \
    --seed 2 \
    --run-name seed2_rerunA \
    --out-dir checkpoints/env_v2_gpsi_heada_ppo_n3pf_ms_block_projected_s2_rerunA \
    --train-steps 1500000 \
    --checkpoint-steps 250000 500000 750000 1000000 1250000 1500000 \
    --n-envs 4 \
    --device cpu \
    --heartbeat-seconds 300 \
    --validate-only

log "Step B seed2_rerunA training starts. This is intentionally single-job CPU training; N4-O is not run in parallel."
run_stage "step_b_train_seed2_rerunA" "${STEP_B_DIR}/logs/phase_n3pf_ms_seed2b_train_seed2_rerunA.log" \
  python scripts/train_env_v2_gpsi_ppo_n3pf_ms_seed2_rerun.py \
    --seed 2 \
    --run-name seed2_rerunA \
    --out-dir checkpoints/env_v2_gpsi_heada_ppo_n3pf_ms_block_projected_s2_rerunA \
    --train-steps 1500000 \
    --checkpoint-steps 250000 500000 750000 1000000 1250000 1500000 \
    --n-envs 4 \
    --device cpu \
    --heartbeat-seconds 300

run_stage "step_b_eval_seed2_rerunA" "${STEP_B_DIR}/logs/phase_n3pf_ms_seed2b_eval_seed2_rerunA.log" \
  python scripts/eval_env_v2_gpsi_ppo_n3pf_ms_seed2_ab.py \
    --mode rerun_eval \
    --result-dir "$RESULT_DIR" \
    --out-dir "$STEP_B_DIR" \
    --runs seed2_rerunA \
    --checkpoints checkpoint_1000k checkpoint_1500k final \
    --eval-seeds 1000 1001 1002 \
    --num-episodes 50 \
    --scenarios "${SCENARIOS[@]}" \
    --device cpu \
    --heartbeat-seconds 300

run_stage "analysis_report" "${LOG_DIR}/phase_n3pf_ms_seed2_ab_analysis.log" \
  python scripts/analyze_env_v2_phase_n3pf_ms_seed2_ab.py \
    --result-dir "$RESULT_DIR" \
    --source-result-dir results/env_v2_phase_n3pf_ms_multiseed \
    --attention-success 0.6033 \
    --attention-collision 0.3967 \
    --noz-success 0.5667 \
    --noz-collision 0.4333 \
    --p3-s0-success 0.6167 \
    --p3-s0-collision 0.3833 \
    --p3-s1-success 0.6089 \
    --p3-s1-collision 0.3911 \
    --p3-s2-success 0.4222 \
    --p3-s2-collision 0.5778

if [[ -f "$COMPLETE_FLAG" ]]; then
  log "COMPLETE ${COMPLETE_FLAG}"
  set_status "complete"
  exit 0
fi

write_watcher_stop "watcher_failed" "analysis finished but complete flag is missing"
log "STOP complete flag missing after analysis"
exit 0
